Add logos
activemerchant/payment_icons pull request #1154
Opened 2024-03-18 09:31 UTC by vponline

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.

Link to the brand guidelines: [Volt Design Guidelines](https://volt.link/design)

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon

![image_720](https://github.com/activemerchant/payment_icons/assets/65347007/f8960122-a921-4e84-b2cc-c4065b36f6d2)

2024-04-03 12:31 UTC, hellicarusprime commented
Hi @vponline there is already an HSBC logo available so you don't need to add another one. Please update and I'll review.

2024-04-08 10:00 UTC, hellicarusprime commented
@vponline I noticed that the icons you want to add are missing a visible border. Please refer to [this section](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance) of our contributing guidelines.

2024-05-16 17:41 UTC, Lovedanihonjin requested changes
Please revise the SVG files:

- You are using an incorrect border radius, The border must have a 2px radius (outside stroke)
- You have the background on top of the border element, which is desaturating the border color.
<img width="556" alt="Screenshot 2024-05-16 at 10 37 12 AM" src="https://github.com/activemerchant/payment_icons/assets/162626251/5c51de9b-ec32-455d-812e-5a4d505cc888">

2024-10-03 17:13 UTC, dannye0231 commented
> Are there any further changes required to get these accepted please?

@vponline are you able to address the following test failures?

Failure:
PaymentIconTest#test_Every_payment_icon_record_has_a_corresponding_SVG_file [test/unit/payment_icon_test.rb:25]:
Expected false to be truthy.

rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:23

..F

Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:89]:
{:message=>"The 'clip0_39_[22](https://github.com/activemerchant/payment_icons/actions/runs/11166377190/job/31040233070?pr=1208#step:4:23)8' ID should be pi-abn-clip0_39_228 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "clip0_39_228".

2024-10-05 12:31 UTC, vponline commented
Ok that should be fixed now

2024-11-04 22:32 UTC, Lydia-shan-git approved these changes

2024-11-04 22:35 UTC, Lydia-shan-git requested changes
Please fix radius on your logo for Sparda-Banken so that it fits within the borders
![sparda](https://github.com/user-attachments/assets/90826a6b-fd4f-4e1d-ab3e-81ad30d4c693)

2024-11-29 10:02 UTC, vponline commented
> Please fix radius on your logo for Sparda-Banken so that it fits within the borders 

I've removed this logo, please review again.

2025-01-07 18:34 UTC, Lydia-shan-git approved these changes

2025-01-08 16:49 UTC, merged

2025-01-09 15:20 UTC, adeniyiao commented
Hi @vponline , 

We noticed quite late that the Barclays and BNP icons appears to be just white rectangle with a blank image. Could you please create a new PR with the updated icons for those two payment methods. Thanks

https://github.com/vponline/payment_icons1111/blob/d99ffffa9ec38f81e00108eb46359b027ddffda3/app/assets/images/payment_icons/bnp.svg

https://github.com/vponline/payment_icons1111/blob/d99ffffa9ec38f81e00108eb46359b027ddffda3/app/assets/images/payment_icons/barclays.svg