banco azteca icon
activemerchant/payment_icons pull request #1175
Opened 2024-04-30 01:02 UTC by alfaro28

## Why are you adding this icons?
I'm adding/updating this icon(s) because Banco Azteca icon is missing and we want to use it for our payment app

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

![Captura desde 2024-04-29 19-01-42](https://github.com/activemerchant/payment_icons/assets/1831607/23c1f8ae-3d51-4fc5-b7de-a3bf10b2accd)

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

2024-05-01 09:02 UTC, Lovedanihonjin requested changes
There is black background on your SVG file. Please fix and outline your stroke. Thank you!

2024-05-08 23:10 UTC, alfaro28 commented
Hi @Lovedanihonjin could you please review again?

2024-05-09 16:20 UTC, Lovedanihonjin requested changes
SVG image is missing border, and border radius is incorrect. Please refer to out appearance guidelines: https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance

<img width="584" alt="Screenshot 2024-05-09 at 9 18 10 AM" src="https://github.com/activemerchant/payment_icons/assets/162626251/7544b223-c195-4bde-9fbd-cc0404962d8d">
<img width="226" alt="Screenshot 2024-05-09 at 9 18 50 AM" src="https://github.com/activemerchant/payment_icons/assets/162626251/2299dea5-6806-44d3-9e9f-5375c34d9a65">

2024-05-09 16:20 UTC, Lovedanihonjin commented on db/payment_icons.yml
> +  name: banco_azteca
We changed our guidelines. Please remove _ from the name.

2024-05-14 19:52 UTC, alfaro28 commented
Hi @Lovedanihonjin could you please review again?

2024-05-23 02:22 UTC, alfaro28 commented
Hi @Lovedanihonjin , I would like to know an estimation of when is this PR going to be merged?

2024-05-28 19:32 UTC, alfaro28 commented
Hi @Lovedanihonjin is there anything we still need to do to have this PR merged?

2024-06-03 15:33 UTC, alfaro28 commented
Hi @Lovedanihonjin I would just like some visibility on why this PR is not being merged despite being approve, and some visibility on an approximate date of release

2024-06-05 13:14 UTC, dannye0231 commented
Hi @alfaro28 , are you able to check the conflicts for this PR?  I am unable to merge it due to an error that needs to be resolved via the command line

2024-06-05 23:21 UTC, alfaro28 commented
Hi @dannye0231 , I fixed the conflicts

2024-06-13 18:22 UTC, alfaro28 commented
Hi @dannye0231 , do you have an estimated date for the next release?

2024-06-17 16:01 UTC, dannye0231 commented
Hi @alfaro28 , we are planning to do another run this Wednesday.  You should see it merged into Prod by the end of this week.

2024-06-19 14:21 UTC, merged