Adding icon Su+ Pay #1205
activemerchant/payment_icons pull request #1206
Opened 2024-07-25 19:33 UTC by shopisumaspay

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

<img src="https://i.ibb.co/fpn23NM/sumas.png" style="width: 10rem"/>

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: black; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<?xml version="1.0" encoding="UTF-8"?>
<svg id="Capa_1" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 342.39 159.57">
  <defs>
    <style>
      .cls-1 {
        fill: url(#Nueva_muestra_de_degradado_1);
      }

      .cls-1, .cls-2 {
        stroke-width: 0px;
      }

      .cls-2 {
        fill: #fff;
      }
    </style>
    <linearGradient id="Nueva_muestra_de_degradado_1" data-name="Nueva muestra de degradado 1" x1="17.6" y1="79.78" x2="324.79" y2="79.78" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f03257"/>
      <stop offset="1" stop-color="#ff6e40"/>
    </linearGradient>
  </defs>
  <path class="cls-1" d="M36.55,17.43h231.31c31.42,0,56.93,25.51,56.93,56.93v10.86c0,31.42-25.51,56.93-56.93,56.93H17.6V36.38c0-10.46,8.49-18.95,18.95-18.95Z"/>
  <path class="cls-2" d="M80.54,90.92c-.04-.45-.08-.89-.15-1.31,0-.05-.02-.1-.03-.16-.06-.38-.13-.75-.21-1.11-.02-.09-.04-.17-.06-.26-.09-.38-.2-.75-.32-1.11,0-.02-.01-.05-.02-.07,0-.02-.02-.04-.02-.06-.01-.04-.03-.07-.04-.1-.12-.33-.24-.65-.38-.96,0,0,0-.02-.01-.03,0,0,0-.02-.01-.02-.05-.11-.1-.22-.15-.33,0,0,0-.02-.01-.03,0-.01-.01-.02-.02-.03-.12-.24-.24-.48-.37-.7,0,0,0-.02-.01-.02,0-.01-.01-.02-.02-.03-.14-.25-.29-.5-.45-.74,0-.01-.02-.03-.03-.04-.5-.75-1.07-1.43-1.7-2.04-.01-.01-.02-.02-.03-.03-.19-.19-.39-.37-.59-.54-.02-.02-.05-.04-.07-.06-.07-.06-.14-.13-.22-.19-.16-.14-.33-.27-.5-.39-.07-.06-.15-.1-.23-.16-.21-.15-.42-.3-.64-.44-.06-.04-.12-.09-.18-.13-.08-.05-.17-.1-.25-.15-.03-.02-.06-.04-.09-.06-.02-.01-.04-.02-.06-.04-.44-.27-.9-.52-1.36-.75-.03-.02-.07-.03-.1-.05-.47-.24-.95-.46-1.44-.67-.03-.01-.06-.03-.09-.04-.49-.21-.99-.41-1.5-.59-.03-.01-.05-.02-.08-.03-.51-.19-1.02-.36-1.53-.53,0,0,0,0-.01,0-.04-.01-.07-.02-.11-.04-.43-.14-.84-.28-1.25-.41-.19-.06-.37-.12-.55-.18-.25-.08-.49-.16-.73-.23-1.43-.46-2.67-.84-3.72-1.2-.07-.02-.14-.05-.21-.07-.23-.08-.46-.16-.67-.23-.1-.03-.19-.07-.28-.1-.18-.07-.35-.13-.52-.2-.1-.04-.19-.07-.28-.11-.15-.06-.3-.12-.43-.18-.09-.04-.17-.08-.25-.11-.13-.06-.26-.13-.38-.19-.07-.04-.14-.07-.21-.11-.12-.07-.24-.14-.35-.21-.05-.03-.1-.06-.15-.1-.3-.21-.54-.42-.74-.66-.02-.02-.04-.05-.06-.07-.09-.11-.17-.23-.23-.35-.01-.02-.02-.04-.03-.07-.06-.11-.11-.23-.15-.35,0-.02-.02-.05-.03-.07-.04-.14-.07-.28-.1-.43,0-.04,0-.07-.01-.11-.02-.15-.03-.31-.03-.47,0,0,0,0,0-.01,0-.02,0-.04,0-.07,0-.15,0-.29.03-.43,0-.05.02-.1.03-.15.02-.11.03-.22.06-.33.01-.05.03-.09.04-.14.03-.11.06-.22.1-.32.01-.04.03-.07.05-.11.05-.11.09-.22.15-.32.01-.03.03-.05.05-.08.06-.11.13-.22.21-.33.01-.02.03-.04.04-.05.08-.11.17-.22.26-.33,0-.01.02-.02.03-.03.1-.11.21-.22.33-.32,0,0,0,0,.01-.01.12-.1.25-.2.39-.3,0,0,0,0,0,0,.12-.08.24-.16.37-.23,0,0,.01,0,.02,0,.12-.07.25-.13.38-.2.01,0,.03-.01.04-.02.13-.06.25-.11.39-.16.03,0,.05-.02.08-.03.12-.04.25-.08.38-.12.04-.01.09-.02.13-.03.12-.03.24-.06.36-.09.07-.01.13-.02.2-.04.11-.02.21-.04.32-.05.1-.01.2-.02.3-.03.08,0,.17-.02.26-.02.19-.01.38-.02.58-.02,0,0,0,0,0,0h0c.34,0,.65.01.96.03.06,0,.13,0,.19.01.29.02.57.04.84.07.04,0,.08.01.12.02.25.03.49.07.72.11.03,0,.06.01.09.02.25.05.49.1.72.15.03,0,.06.01.09.02.98.24,1.81.55,2.62.83.98.34,1.94.64,3.15.74.03,0,.06,0,.09,0,.26.02.52.03.8.03.23,0,.46-.02.68-.04.07,0,.14-.02.2-.03.15-.02.3-.05.45-.08.07-.02.15-.03.22-.05.14-.04.28-.08.42-.13.06-.02.12-.04.18-.07.19-.08.37-.16.54-.25,0,0,0,0,0,0,0,0,0,0,0,0,.17-.1.34-.2.5-.32.05-.04.1-.08.15-.12.11-.08.21-.17.32-.27.05-.05.1-.1.15-.15.1-.1.19-.2.28-.31.04-.05.08-.1.12-.15.12-.16.24-.32.34-.49,0,0,0,0,0,0,0,0,0,0,0,0,.12-.2.23-.42.33-.64.02-.06.05-.11.07-.17.18-.45.31-.94.39-1.46,0-.06.02-.13.02-.2.03-.26.05-.53.05-.81,0-.24-.02-.47-.05-.7-.02-.21-.07-.41-.11-.61,0,0,0,0,0,0s0,0,0,0c-.26-1.1-.85-2.11-1.76-3-.04-.03-.07-.07-.11-.1-.15-.14-.31-.28-.48-.41-.06-.05-.12-.1-.18-.14-.17-.13-.34-.25-.52-.38-.06-.04-.13-.08-.19-.12-.35-.22-.73-.43-1.14-.63-.09-.04-.18-.09-.27-.13-.18-.08-.37-.16-.55-.23-.16-.06-.31-.13-.48-.19-.18-.07-.36-.13-.55-.19-.19-.06-.39-.13-.6-.19-.18-.05-.35-.11-.53-.15-.29-.08-.59-.15-.89-.21-.14-.03-.28-.06-.42-.09-.39-.08-.8-.15-1.21-.21-.16-.02-.32-.04-.48-.07-.32-.04-.64-.08-.97-.12-.18-.02-.36-.03-.54-.05-.35-.03-.7-.05-1.06-.07-.17,0-.33-.02-.5-.03-.53-.02-1.07-.04-1.63-.04h0c-5.09,0-9.92,1.38-13.48,4.22,0,0,0,0-.01,0-.29.23-.57.48-.84.73-.07.07-.14.13-.21.2-.27.26-.53.52-.78.8,0,0-.02.02-.02.03-.25.28-.48.57-.71.86-.06.08-.12.16-.18.24-.22.3-.43.6-.63.92,0,0-.01.02-.02.02-.01.02-.02.04-.03.05-.16.26-.32.53-.46.81-.05.1-.1.2-.16.31-.1.2-.2.41-.3.62-.05.12-.1.23-.15.35-.09.21-.17.43-.25.65-.04.11-.08.22-.12.34-.11.31-.21.63-.3.96-.01.04-.02.08-.03.12-.09.33-.16.66-.23,1-.03.12-.05.25-.07.38-.05.25-.09.5-.12.75-.02.14-.04.29-.06.43-.03.26-.05.52-.07.78-.01.14-.02.27-.03.42-.02.37-.03.74-.03,1.12,0,.03,0,.06,0,.09,0,.05,0,.1,0,.16,0,.25,0,.5.02.75,0,.12.01.23.02.35.01.18.02.36.04.53.01.12.02.24.04.36.02.16.04.32.06.48.02.12.03.23.05.34.03.16.06.32.09.48.02.1.04.2.06.3.04.19.09.37.13.55.02.06.03.13.05.19.07.24.14.47.22.7.02.06.04.11.06.17.06.17.12.34.19.5.03.07. [...]

2024-08-19 18:56 UTC, claudiomunoz commented
The icon doesn't follow our submission guidelines:  
- Transparent backgrounds will not be accepted
- Icons should have a visible border to give them a consistent shape on pages whose backgrounds match that of the icon 
- Icons should be optimize using SVGO.

See the submission [guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons) for more details.

2024-09-20 19:11 UTC, shopisumaspay commented
The changes are already uploaded.

2024-09-30 18:36 UTC, dannye0231 commented
Hi @shopisumaspay , are you able to resolve the following issue in the SVG file?

Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:81]:
{:message=>"The 'sumas_pay' SVG file does not have the appropriate 'id' value on the <title> tag"}.
Expected: "pi-sumas_pay"
  Actual: "pi-sumas-pay"

2024-10-17 20:06 UTC, dannye0231 commented
Hi @shopisumaspay , there still seems to be an issue with this SVG:

Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:89]:
{:message=>"The 'clippath' ID should be pi-sumas_pay-clippath (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "clippath".

2024-11-04 22:26 UTC, Lydia-shan-git requested changes
It looks like your borders are thinner and there might be 2 borders. Please make sure your border width and style match those in the guidelines

2025-01-27 21:36 UTC, dannye0231 commented
Hi @shopisumaspay , any updates?  Also, can you please re-base?

2025-04-02 16:07 UTC, dannye0231 commented
Closed due to lack of communication

2025-04-02 16:07 UTC, closed without merging