feat: Add new icons for efecty, nequi and yape, also fix Visa icon th…
activemerchant/payment_icons pull request #1221
Opened 2024-08-20 15:09 UTC by Candres1019

## Why are you adding this icons?
Added new icons for Nequi, Efecty, and Yape—Colombian and Peruvian payment methods, respectively. These icons will be used by PayU. Also, corrected inconsistencies and defects in the Visa logo, ensuring uniformity in letter colors and clarity.

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines:

### Colombia:
Nequi - https://www.nequi.com.co/
Efecty - https://www.efecty.com.co/web/

### Peru
Yape - https://www.yape.com.pe/

### Global
Visa - https://www.merchantsignage.visa.com/brand_guidelines

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon

<img width="788" alt="image" src="https://github.com/user-attachments/assets/9201944d-b7cc-45bf-b0a2-d21f0928ea10">

What's the expected date of this change to deploy on Shopify? < 3 Days

2024-08-30 15:42 UTC, adeniyiao commented
Hi @Candres1019,

Kindly address the test failure as seen below

```
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:89]:
{:message=>"The 'Capa_1' ID should be pi-efecty-Capa_1 (missing 'pi-' prefix)"}.
Expected /pi-(.*)/ to match "Capa_1".

```

2024-08-31 01:17 UTC, Candres1019 commented
Hi @adeniyiao , 

Thanks for the comments, i just made the changes to add the pi preffix in the ids

2024-09-02 14:21 UTC, dani-ooo commented
hello. i'm not very experienced with pull requests, so i'm wondering if this will be an issue:
i have a previous open pull request updating the Visa icon as well #1210.

i also have (i believe) slightly better icons for Nequi and Efecty ready, but i didn't submit because i wasn't sure whether they'd be approved based on the Shopify Partners disclaimer. how could i propose those, without affecting this pull request.

2024-09-20 14:39 UTC, dannye0231 commented
Hi @Candres1019 , are you able to check the SVGs and correct the naming errors when are coming up in the tests?  I already fixed a few issues within the YML file and and Visa icon but there are still additional errors coming up in the remaining SVGs.

2024-09-20 22:36 UTC, Candres1019 commented
Hi @dannye0231 , thank u , i just did the changes that are mention in the test

2024-09-21 01:23 UTC, dannye0231 commented
Hi @Candres1019 , are you able to check one more error that is showing up?

"The 'Capa_1' ID should be pi-yape-Capa_1 (missing 'pi-' prefix)"}.

2024-09-21 01:51 UTC, Candres1019 commented
Hi @dannye0231 , sure, done

2024-11-14 22:33 UTC, Candres1019 commented
Hi @Lydia-shan-git , can we do the merge of this branch ?

2024-11-15 01:26 UTC, Lydia-shan-git requested changes
Looks good, just pass each icon into SVGO to reduce it's size

2024-11-15 01:29 UTC, Lydia-shan-git commented on app/assets/images/payment_icons/visa.svg
@dannye0231 We're not changing major card icons right?

2024-11-22 19:06 UTC, dannye0231 commented on app/assets/images/payment_icons/visa.svg
Correct, these PRs would only apply to the individual payment integration icons.

2024-12-02 18:32 UTC, dannye0231 commented on app/assets/images/payment_icons/visa.svg
Hi @Candres1019 , are you able to omit the Visa icon change from this PR and only keep your payment integration icon in scope?

2024-12-09 14:10 UTC, andres-calderon-payu-gpo commented on app/assets/images/payment_icons/visa.svg
hey @dannye0231 , done, i just remove the Visa Icon change

2025-01-08 19:15 UTC, merged