[Managed Markets] Adding payment icon for KCP Credit Card
activemerchant/payment_icons pull request #1244
Opened 2024-10-21 05:40 UTC by mseal-shopify

## Why are you adding this icons?
I'm adding a new payment icon for KCP.

https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/kcp_creditcard.svg

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

2024-10-21 17:52 UTC, Lydia-shan-git requested changes
Make sure the entire logo fits within the borders. Currently, you have a green square that overlaps on top of the border by a smidge. Other than everything else looks good

2024-11-04 16:06 UTC, Lydia-shan-git requested changes
Looking good! Just run it through SVGO so it's the smallest possible file size

2024-11-04 19:44 UTC, Lydia-shan-git approved these changes

2024-11-07 14:43 UTC, adeniyiao commented
Hi @mseal-shopify , just a quick observation, for `kcp_creditcard`, the icon name and filename should be lowercase alpha characters only as per the [guide](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#name).

Thanks

2024-11-12 00:08 UTC, mseal-shopify commented
> Hi @mseal-shopify , just a quick observation, for `kcp_creditcard`, the icon name and filename should be lowercase alpha characters only as per the [guide](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#name).
> 
> Thanks

Thanks pointing that out, but I see there are other icons as well with underscore in their names. Is that something that's not allowed?

2024-12-04 18:19 UTC, adeniyiao commented
Hi @mseal-shopify , sorry for the late response. Previously underscore was accepted for the old icons, but new icons should not have underscore as per latest guide.

2025-01-08 16:34 UTC, merged