Add bancolombia icon
activemerchant/payment_icons pull request #1259
Opened 2024-12-03 15:35 UTC by tamfrazzetta

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
![{3B568898-19EF-4A58-B870-4F9573C7C4A3}](https://github.com/user-attachments/assets/d30b870e-4bd8-4173-9974-5ad158f6e6e5)

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: black; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_10213_23)"><mask id="mask0_10213_23" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="38" height="24"><path d="M38 0H0v24h38V0z" fill="#fff"/></mask><g mask="url(#mask0_10213_23)" stroke="#000"><path d="M36 0H2a2 2 0 00-2 2v20a2 2 0 002 2h34a2 2 0 002-2V2a2 2 0 00-2-2z" fill="#fff" stroke-opacity=".07"/><path fill-rule="evenodd" clip-rule="evenodd" d="M24.685 16.515a71.279 71.279 0 00-7.165 2.155c-.337.127-.702-.038-.791-.361-.19-.689-.358-1.218-.546-1.904a.602.602 0 01.389-.71c2.356-.804 4.735-1.436 7.168-1.96.268-.055.55.143.647.445.197.615.368 1.11.56 1.727.086.28-.029.552-.262.608zM12.491 15.2c-.144-.74-.289-1.296-.43-2.035-.055-.289.102-.617.365-.74 3.598-1.581 7.393-2.538 11.29-3.031.257-.033.517.156.612.44.206.608.381 1.1.58 1.712.097.295-.031.582-.283.623-3.963.63-7.826 1.689-11.48 3.351-.294.142-.592-.003-.654-.32zm1.752-8.415c2.41-.693 4.816-1.144 7.305-1.448a.622.622 0 01.635.413c.232.63.42 1.132.646 1.766.107.3-.052.6-.344.64-2.548.374-5.017.889-7.48 1.641-.3.1-.595-.052-.671-.344-.18-.691-.342-1.223-.518-1.912a.647.647 0 01.427-.756zM19 1C12.925 1 8 5.925 8 12s4.925 11 11 11 11-4.925 11-11S25.075 1 19 1z" fill="#2C2A29" stroke-opacity=".01" stroke-width=".1"/></g></g><defs><clipPath id="clip0_10213_23"><path fill="#fff" d="M0 0h38v24H0z"/></clipPath></defs></svg>

<br>

<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_10213_23)"><mask id="mask0_10213_23" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="38" height="24"><path d="M38 0H0v24h38V0z" fill="#fff"/></mask><g mask="url(#mask0_10213_23)" stroke="#000"><path d="M36 0H2a2 2 0 00-2 2v20a2 2 0 002 2h34a2 2 0 002-2V2a2 2 0 00-2-2z" fill="#fff" stroke-opacity=".07"/><path fill-rule="evenodd" clip-rule="evenodd" d="M24.685 16.515a71.279 71.279 0 00-7.165 2.155c-.337.127-.702-.038-.791-.361-.19-.689-.358-1.218-.546-1.904a.602.602 0 01.389-.71c2.356-.804 4.735-1.436 7.168-1.96.268-.055.55.143.647.445.197.615.368 1.11.56 1.727.086.28-.029.552-.262.608zM12.491 15.2c-.144-.74-.289-1.296-.43-2.035-.055-.289.102-.617.365-.74 3.598-1.581 7.393-2.538 11.29-3.031.257-.033.517.156.612.44.206.608.381 1.1.58 1.712.097.295-.031.582-.283.623-3.963.63-7.826 1.689-11.48 3.351-.294.142-.592-.003-.654-.32zm1.752-8.415c2.41-.693 4.816-1.144 7.305-1.448a.622.622 0 01.635.413c.232.63.42 1.132.646 1.766.107.3-.052.6-.344.64-2.548.374-5.017.889-7.48 1.641-.3.1-.595-.052-.671-.344-.18-.691-.342-1.223-.518-1.912a.647.647 0 01.427-.756zM19 1C12.925 1 8 5.925 8 12s4.925 11 11 11 11-4.925 11-11S25.075 1 19 1z" fill="#2C2A29" stroke-opacity=".01" stroke-width=".1"/></g></g><defs><clipPath id="clip0_10213_23"><path fill="#fff" d="M0 0h38v24H0z"/></clipPath></defs></svg>

</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

2025-01-07 17:20 UTC, Lydia-shan-git reviewed
Please make sure your border is 1 px thick and follows a radius of 2px as in the [guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance)

2025-01-07 17:20 UTC, Lydia-shan-git requested changes
Please make sure your border is 1 px thick and follows a radius of 2px as in the [guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#appearance)

2025-01-27 20:48 UTC, dannye0231 commented
@tamfrazzetta can you please re-base this PR?

2025-01-27 20:49 UTC, dannye0231 commented
@tamfrazzetta can you please fix the following issue with your SVG file?

Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:93]:
{:message=>"The 'bancolombia' SVG file should have a 'role' attribute on the root <svg> tag"}

2025-01-27 21:07 UTC, tamfrazzetta commented
> @tamfrazzetta can you please fix the following issue with your SVG file?
> 
> Failure: PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:93]: {:message=>"The 'bancolombia' SVG file should have a 'role' attribute on the root tag"}

Done and rebased 👌

2025-01-27 22:03 UTC, dannye0231 commented
@Lydia-shan-git are you able to review again, as changes have been made?

2025-02-17 16:00 UTC, tamfrazzetta commented
@dannye0231 @Lydia-shan-git  I've re-based this PR

2025-03-07 12:54 UTC, tamfrazzetta commented
@Lydia-shan-git @dannye0231  Would you be able to provide an estimated timeframe for when we can expect this payment method icon to be added?

2025-03-07 14:38 UTC, dannye0231 commented
Hi @tamfrazzetta , we are aiming for next Wednesday as we are still trying to go through and get all of the approvals needed before merging.

2025-03-31 17:15 UTC, dannye0231 commented
@tamfrazzetta can you please check the following issues:

Inline Styles: ❌ (There are no styles, but the opacity is set in the attribute instead of a style). Inline Styles: Ensure that any style attributes are set inline, though the current SVG does not have a <style> tag, the opacity should be reviewed.
Border Width: ❌ (The border width of the inner rectangle is not 1px; it should be adjusted)
Border Radius: ❌ (The border radius is set to 2.5px, but it should be 2px)

2025-03-31 17:50 UTC, tamfrazzetta commented
@dannye0231 Done 👍

2025-03-31 21:11 UTC, dannye0231 approved these changes
File Format

[✓] SVG format is appropriate for vector graphics.
Accessibility

[✓] <title> element present for screen readers (id: pi-bancolombia).
[✓] role="img" attribute correctly used.
Dimensions

[✓] viewBox is set to "0 0 38 24."
[✓] Width and height attributes match the viewBox dimensions (38x24).
Clipping and Paths

[✓] Paths are well-defined and appear to be closed properly.
[✓] Correct use of fill-rule and clip-rule.
Semantic Structure

[✓] Appropriate use of <rect> and <path> elements.
[✓] Rounded corners applied correctly with rx attribute.
Color Usage

[✓] Main path filled with dark gray (#2C2A29) provides good contrast against white.

2025-04-02 15:27 UTC, merged