add daviplata icon
activemerchant/payment_icons pull request #1261
Opened 2024-12-03 15:58 UTC by tamfrazzetta

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
![{4D8235B3-EB1F-43EB-84FD-94E6614B8052}](https://github.com/user-attachments/assets/1ac4d1df-e706-4807-a7f8-3148b15f5b7d)

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: white; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_10213_30)"><mask id="mask0_10213_30" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="38" height="24"><path d="M38 0H0v24h38V0z" fill="#fff"/></mask><g mask="url(#mask0_10213_30)"><path d="M36 0H2a2 2 0 00-2 2v20a2 2 0 002 2h34a2 2 0 002-2V2a2 2 0 00-2-2z" fill="#fff" stroke="#000" stroke-opacity=".07"/><path d="M19.791 11.796c0-.36-.01-.653-.023-.92h.46l.024.484h.011c.21-.344.542-.547 1.002-.547.682 0 1.195.577 1.195 1.432 0 1.013-.617 1.515-1.282 1.515-.373 0-.7-.163-.868-.443h-.011v1.531h-.508v-3.052zm.508.75a.792.792 0 00.793.81c.54 0 .856-.442.856-1.088 0-.564-.297-1.048-.84-1.048-.349 0-.675.25-.774.634a.819.819 0 00-.034.21l-.002.483zM23.106 9.56h.512v4.134h-.512V9.56zM26.042 13.694L26 13.34h-.018c-.158.22-.46.42-.863.42-.57 0-.862-.402-.862-.81 0-.682.606-1.055 1.695-1.049v-.059c0-.233-.064-.652-.64-.652-.263 0-.537.08-.734.21l-.117-.338c.233-.15.57-.25.926-.25.862 0 1.072.588 1.072 1.152v1.054c0 .244.011.484.047.676l-.465.001zm-.076-1.438c-.56-.01-1.194.088-1.194.635 0 .332.22.49.484.49a.7.7 0 00.681-.472.525.525 0 00.03-.164v-.489zM27.883 10.066v.81h.734v.39h-.734v1.52c0 .35.099.548.384.548.134 0 .233-.018.298-.035l.023.384c-.099.041-.256.07-.454.07-.239 0-.43-.075-.554-.215-.145-.151-.197-.402-.197-.734v-1.538h-.438v-.39h.438V10.2l.5-.134zM30.755 13.694l-.041-.355h-.018c-.158.22-.46.42-.863.42-.57 0-.862-.402-.862-.81 0-.682.606-1.055 1.695-1.049v-.059c0-.233-.064-.652-.64-.652-.263 0-.537.08-.734.21l-.117-.338c.233-.15.57-.25.926-.25.862 0 1.072.588 1.072 1.152v1.054c0 .244.011.484.047.676l-.465.001zm-.076-1.438c-.56-.01-1.194.088-1.194.635 0 .332.22.49.484.49a.7.7 0 00.681-.472.525.525 0 00.03-.164v-.489zM10.604 9.817c-1.02-.028-2.338 2.622-2.686 3.501-.197.49.41.843.606.353.324-.817 1.432-3.095 2.081-3.09.65.003 1.72 2.293 2.036 3.113.19.493.8.147.61-.346-.34-.883-1.628-3.548-2.647-3.53zM7.87 11.736a1.806 1.806 0 00-.317-.816l-.036-.047a2.344 2.344 0 00-.153-.18l-.018-.017c-1.073-1.06-3.41-.952-4.08-.67-.45.19-.295.75.2.532a4.736 4.736 0 012.376 0c.65.163 1.329.73 1.329 1.339-.047 1.518-2.055 1.577-2.87 1.38v-1.889c0-.45-.58-.454-.58-.003v1.899c0 .381.196.519.457.579.613.14 3.187.29 3.644-1.538.01-.035.016-.069.023-.103.006-.031.013-.062.017-.095.018-.124.02-.241.011-.352 0-.007-.002-.013-.003-.02zm10.795-1.508c0-.526-.662-.524-.662-.009v3.319c0 .497.662.516.662.019v-3.33zm-1.656-.192c-.289.822-1.28 3.114-1.88 3.121-.6.006-1.623-2.268-1.928-3.083-.183-.49-.741-.135-.56.355.328.877 1.56 3.524 2.502 3.492.942.014 2.12-2.657 2.432-3.54.173-.493-.392-.838-.566-.345z" fill="#2C2A29"/><path d="M33.972 8.26a41.203 41.203 0 00-1.649-1.28 7.9 7.9 0 01.197-1.196c.105-.42.197-.781 0-1.034-.134-.17-.366-.25-.732-.25h-1.366c-.311 0-.536.09-.672.267a.704.704 0 00-.12.51C28.161 4.478 26.89 4.004 26.185 4h-.002c-.757.004-2.167.55-3.772 1.46-.228.128-1.615.947-2.288 1.465-.01.008-1.114.806-1.726 1.319a4.13 4.13 0 00-.665.687.169.169 0 00.13.275.167.167 0 00.128-.062s.049-.064.08-.109c.142-.174.32-.354.54-.538.6-.505 1.695-1.296 1.71-1.307.661-.51 2.029-1.316 2.253-1.442 1.557-.883 2.907-1.412 3.61-1.417.703.004 2.052.533 3.61 1.417a.165.165 0 00.242-.181c-.008-.04-.02-.08-.032-.119l-.019-.067c-.028-.103-.063-.294.028-.413.086-.114.27-.137.409-.137h1.366c.245 0 .409.042.47.123.098.126.022.43-.06.751a8.262 8.262 0 00-.212 1.343.163.163 0 00.066.144c.011.008 1.11.816 1.706 1.32.726.613 1.035 1.183.867 1.607-.185.47-.958.754-1.92.706l-.336-.017-.21-.01a.164.164 0 00-.122.047.168.168 0 00-.05.122c.013.525.169 1.584 1.06 2.785.801.956.92 2.063.325 3.036-.71 1.163-2.489 2.098-4.86 1.564a.162.162 0 00-.09.005c-.646.216-1.698.312-2.238.312s-1.592-.097-2.238-.313a.165.165 0 00-.089-.004c-2.374.535-4.153-.402-4.863-1.564-.386-.633-.467-1.322-.257-1.992 0 0 .01-.037.006-.064v-.01a.16.16 0 00-.13-.138.16.16 0 00-.173.075l-.002.005c-.019.03-.035.104-.035.104a2.713 2.713 0 00.31 2.191c.621 1.018 1.98 1.878 3.808 1.878.43 0 .887-.048 1.365-.152.72.23 1.785.315 2.298.315.512 0 1.578-.087 2.299-.315 2.51.548 4.404-.468 5.171-1.724.663-1.085.53-2.365-.348-3.412-.74-.998-.937-1.885-.98-2.411h.025l.337.018c1.121.055 2.003-.302 2.244-.915.157-.4.12-1.07-.962-1.98h.002z" fill="#2C2A29"/><path d="M19.791 11.796c0-.36-.01-.653-.023-.92h.46l.024.484h.011c.21-.344.542-.547 1.002-.547.682 0 1.195.577 1.195 1.432 0 1.013-.617 1.515-1.282 1.515-.373 0-.7-.163-.868-.443h-.011v1.531h-.508v-3.052zm.508.75a.792.792 0 00.793.81c.54 0 .856-.442.856-1.088 0-.564-.297-1.048-.84-1.048-.349 0-.675.25-.774.634a.819.819 0 00-.034.21l-.002.483zM23.106 9.56h.512v4.134h-.512V9.56zM26.042 13.694L26 13.34h-.018c-.158.22-.46.42-.863.42-.57 0-.862-.402-.862-.81 0-.682.606-1.055 1.695-1.049v-.059c0-.233-.064-.652-.64-.652-.263 0-.537.08-.734.21l-.117-.338c.233-.15.57-.25.926-.25.862 0 1.072.588 1.072 1.152v1.054c0 .244.011.484.047.676l-.465.001zm-.076-1.438c-.56-.01-1.194.088-1.194.635 0 .332.22.49.484.49a.7.7 0 0 [...]

2024-12-20 12:23 UTC, tamfrazzetta commented
Would it be possible to receive feedback for this PR and an estimated time of when we could hope to have this payment method icon added?

2025-01-07 17:17 UTC, Lydia-shan-git requested changes
Please make sure your border is 1 px thick and your radius is 2px as outlined in the [guidelines](The border width must be 1px (pixel) thick.
The border must have a 2px radius (outside stroke).)

2025-01-27 20:46 UTC, dannye0231 commented
@tamfrazzetta can you please re-base this PR?

2025-01-27 21:04 UTC, tamfrazzetta commented
> @tamfrazzetta can you please re-base this PR?

Done👌

2025-01-27 22:07 UTC, dannye0231 commented
@tamfrazzetta are you able to address the following error in your SVG file?

Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:78]:
{:message=>"The 'daviplata' SVG file does not have the appropriate <title> value"}.
Expected: "DaviPlata"
  Actual: "Daviplata"

rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:61

2025-01-28 14:03 UTC, tamfrazzetta commented
> @tamfrazzetta are you able to address the following error in your SVG file?
> 
> Failure: PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [test/unit/payment_icon_test.rb:78]: {:message=>"The 'daviplata' SVG file does not have the appropriate <title> value"}. Expected: "DaviPlata" Actual: "Daviplata"
> 
> rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:61

Done👌

2025-02-03 20:39 UTC, Lydia-shan-git approved these changes

2025-02-05 13:57 UTC, merged