UnionPay QuickPass Logo
activemerchant/payment_icons pull request #354
Opened 2020-09-27 04:09 UTC by LaNeraNura

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

2020-10-29 13:43 UTC, tauthomas01 requested changes
Hi @LaNeraNura ,

There seems to be SVG markup error. I can't view the file.

Can you please fix the errors?

2020-11-01 13:01 UTC, LaNeraNura commented
Hi Thomas, 
I have recreated the svg file. Kindly take a look if this format can be viewed now.
Thanks!

2020-11-04 21:42 UTC, tauthomas01 requested changes

2020-11-04 21:42 UTC, tauthomas01 commented on app/assets/images/payment_icons/unionpay_quickpass.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" aria-labelledby="pi-unionpay_quickpass" height="24" width="38" viewBox="0 0 38 24" role="img" id="svg8
Can we remove unused `id` attributes if it's not used? I see some instances:

- `path834`
- `path836`

Also is the `<defs></defs>` needed?

2020-11-08 11:20 UTC, LaNeraNura commented
Hi Thomas, both paths are in use and cannot be deleted. But I have deleted the `<defs></defs>` attribute.

2020-11-09 15:10 UTC, tauthomas01 commented
Hi @LaNeraNura , it's okay to keep the `path` for usage, but what I meant is removing the `id` attributes

[![alt](https://screenshot.click/09-09-8nhc4-zwvqj.png)](https://screenshot.click/09-09-8nhc4-zwvqj.png)

2020-11-15 11:58 UTC, LaNeraNura commented
Okay, I deleted the IDs.

2020-11-18 21:04 UTC, tauthomas01 requested changes
Hi @LaNeraNura ,

I still see some `id` instances that are not used. Can we make sure that all unused `id` attributes are removed?
For example `image902`.

The rest looks good.

2020-11-22 06:32 UTC, LaNeraNura commented
Okay I removed the `image902`

2022-09-16 16:37 UTC, rahilvirani commented
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

2022-09-16 16:37 UTC, closed without merging