Alchemy Logo
activemerchant/payment_icons pull request #357
Opened 2020-09-27 08:57 UTC by LaNeraNura

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

2020-10-29 13:56 UTC, tauthomas01 requested changes
Hi,

I left some comments.

Please let me know if there are any questions.

2020-10-29 13:56 UTC, tauthomas01 commented on app/assets/images/payment_icons/alchemy.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" aria-labelledby="pi-alchemy" height="24" width="38" viewBox="0 0 38 24" role="img" id="svg840"><defs i
There a few elements that I don't see used.

- `<path id="path836">`
- `<path id="rect866">`
- `<clipPath id="clipPath864">`
- `<path id="rect891">`

Can we also remove `id="svg840"`?

In summary, can we please remove anything that is not used?

2020-11-08 12:03 UTC, LaNeraNura commented
Hi Thomas, I have re-generated the icon. Kindly check again.

2020-11-09 15:08 UTC, tauthomas01 requested changes
Hi, I still see some `defs` and `id` that are unused. Can you please check and remove those attributes if there are unused?
Thank you

2020-11-15 12:06 UTC, LaNeraNura commented
Okay, I have deleted the parameters.

2020-11-18 21:07 UTC, tauthomas01 commented
Hi @LaNeraNura ,

I still see some `id` instances that are not used. Can we make sure that all unused `id` attributes are removed?

Also, I noticed I can't view the SVG file (it's freezing when I view on Chrome). It seems like the file is oddly heavy (466kb) which is really big for a SVG file.

Can you check if we can remove things that are hidden or not used?

2020-11-18 21:09 UTC, tauthomas01 commented on app/assets/images/payment_icons/alchemy.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" aria-labelledby="pi-fps" height="24" width="38" viewBox="0 0 38 24" role="img" id="svg17"><defs><title
Also, I see `pi-fps` and FPS as the title. Should we rename to `pi-alchemy` and Alchemy as title?

2022-09-16 16:37 UTC, rahilvirani commented
Closing the PR because it has been stale for a while. If the change is still relevant, please re-create the pull request using the new pull request template. We are sorry for the inconvenience.

2022-09-16 16:37 UTC, closed without merging