payment icons updated
activemerchant/payment_icons pull request #413
Opened 2021-02-11 06:26 UTC by maunaw

** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

2021-02-16 10:50 UTC, larouxn requested changes
There are a few issues we need to address.
- Mastercard does not need to be added, it already exists as [master](https://github.com/activemerchant/payment_icons/blob/cc59fa2b339561885ce33069ba63304108d56b6a/app/assets/images/payment_icons/master.svg).
- Why are we updating PayPal, Visa, and Maestro? Seems unnecessary. (also weird spacing)
- Why are we updating the Afterpay icon? It's currently correct according to https://www.afterpay.com. Do we need a _new_ afterpay icon for a different similarly named service?
- Why is the Swish icon update blank? (pure white)
- Why do all icons have an empty space towards the bottom? (see below)
![space](https://user-images.githubusercontent.com/1557529/108052570-af61f980-708f-11eb-983e-2ed717b994a1.png)

2021-02-18 06:12 UTC, maunaw commented
> There are a few issues we need to address.
> 
> * Mastercard does not need to be added, it already exists as [master](https://github.com/activemerchant/payment_icons/blob/cc59fa2b339561885ce33069ba63304108d56b6a/app/assets/images/payment_icons/master.svg).
> * Why are we updating PayPal, Visa, and Maestro? Seems unnecessary. (also weird spacing)
> * Why are we updating the Afterpay icon? It's currently correct according to https://www.afterpay.com. Do we need a _new_ afterpay icon for a different similarly named service?
> * Why is the Swish icon update blank? (pure white)
> * Why do all icons have an empty space towards the bottom? (see below)
>   ![space](https://user-images.githubusercontent.com/1557529/108052570-af61f980-708f-11eb-983e-2ed717b994a1.png)


Hi, @larouxn Thank you for the response. Changes have been made as per suggestions. Can you please take a look at latest commit?

2021-02-22 02:40 UTC, larouxn commented
👋 Hey @maunaw, can we do the following?
- Remove the changes to Afterpay, Maestro, PayPal, and Visa
- Remove the new, unnecessary Mastercard SVG
- Fix all of the added/updated icons so they have the proper 7% visible gray border ([guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons) | [template](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#template))
- Run SVGO on all of the added/updated icons ([step 5 in here](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#contributing))

2021-02-24 08:05 UTC, momai-nets commented
Hi Nicholas,
Thank you for your feedback.

    Remove the changes to Afterpay, Maestro, PayPal, and Visa
    Remove the new, unnecessary Mastercard SVG
    **- Former versions did not follow the guideline fully because of transparent background. Therefore we are surprised by this** comment
    Fix all of the added/updated icons so they have the proper 7% visible gray border (guidelines | template)
   **- All icons consists of background#fff and 1px border #000 0.07transparency border-radius 2px ??**
    Run SVGO on all of the added/updated icons (step 5 in here)
   **- Please check content of SVG files. All files are fully optimized.**

2021-02-24 10:03 UTC, larouxn commented
👋  Hello @momai-nets, the updated Afterpay icon is still the wrong icon. It should be the icon for [afterpay.com](https://www.afterpay.com/index). Additionally, Maestro and other icons are still less tall for some reason. This is not desirable. Can we please remove the Afterpay, Maestro, PayPal, and Visa changes as well as the added Mastercard icon?
<img width="111" alt="Screen Shot 2021-02-24 at 18 48 02" src="https://user-images.githubusercontent.com/1557529/108982233-ea3be100-76d0-11eb-800a-bd366827afa1.png">
<img width="112" alt="Screen Shot 2021-02-24 at 18 48 12" src="https://user-images.githubusercontent.com/1557529/108982238-eb6d0e00-76d0-11eb-9dcc-567ce1ef0f99.png">

Additionally it seems the updated icons do not seem to have the proper border style.
<img width="104" alt="Screen Shot 2021-02-24 at 18 51 18" src="https://user-images.githubusercontent.com/1557529/108982997-be6d2b00-76d1-11eb-9b1b-f02bf1761795.png">
<img width="116" alt="Screen Shot 2021-02-24 at 18 51 31" src="https://user-images.githubusercontent.com/1557529/108983000-bf05c180-76d1-11eb-9597-6b4c4a330aa0.png">

The Visa icon can be used as a guideline. Newly added/updated icons should adhere to this style. If we look carefully, we can see the updated icons do not have the same border style as the grey border is visible upon the black background.
<img width="225" alt="Screen Shot 2021-02-24 at 18 53 55" src="https://user-images.githubusercontent.com/1557529/108982971-b614f000-76d1-11eb-954e-b11e1ab5a3bd.png"><img width="195" alt="Screen Shot 2021-02-24 at 18 54 02" src="https://user-images.githubusercontent.com/1557529/108982976-b7461d00-76d1-11eb-9323-c51e089573b7.png">
<img width="219" alt="Screen Shot 2021-02-24 at 18 57 26" src="https://user-images.githubusercontent.com/1557529/108983472-405d5400-76d2-11eb-9adc-2d492dfe7368.png"><img width="211" alt="Screen Shot 2021-02-24 at 18 58 05" src="https://user-images.githubusercontent.com/1557529/108983476-418e8100-76d2-11eb-9d42-4b37910f530c.png">

Lastly, I feel SVGO likely has not been run on the icons as SVGO compresses icons to a single line, whereas all of these updated/added icons are multi-line. Though, this is the least of my concerns.

---

All of that said, I am somewhat okay the changes to the icons _other than_ Afterpay, Maestro, PayPal, Visa, and Mastercard.

2021-02-25 09:40 UTC, momai-nets commented
Arh Thank you Nicolas,
I see the issue now from your screenshots. The batch of icons you are working with are NOT the latest batch where we have fixed all issues and followed the guidelines fully. We will look into it.

2021-03-03 06:23 UTC, maunaw commented
@larouxn We have updated the icons running SVGO and restoring old ones. Request you to please review the updated icons with latest commit. Kindly let us know if anything. Thank you.

2021-03-03 14:09 UTC, larouxn commented
👋 I will try to take a look at this tomorrow. In the meantime, can we remove the `mastercard.svg`? There's already an icon available at `master.svg`.

https://github.com/activemerchant/payment_icons/blob/2c77ec6a6d17ab352b411b4d8b5411b2b82e95b2/app/assets/images/payment_icons/master.svg

2021-03-03 14:18 UTC, maunaw commented
> 👋 I will try to take a look at this tomorrow. In the meantime, can we remove the `mastercard.svg`? There's already an icon available at `master.svg`.
> 
> https://github.com/activemerchant/payment_icons/blob/2c77ec6a6d17ab352b411b4d8b5411b2b82e95b2/app/assets/images/payment_icons/master.svg

Sure, removed mastercard.svg. Thank you.

2021-03-05 02:11 UTC, larouxn approved these changes
Thanks for cleaning this up! Looking good.
<img width="846" alt="Screen Shot 2021-03-05 at 11 10 15" src="https://user-images.githubusercontent.com/1557529/110057175-7b7f1780-7da3-11eb-9502-9f3434a267e1.png">

@tauthomas01, can you take a look?

2021-03-05 15:44 UTC, tauthomas01 requested changes

2021-03-05 15:44 UTC, tauthomas01 commented on app/assets/images/payment_icons/dankort.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-dankort"><title id="pi-dankort">Dankort</title><g fill-rule="evenodd" clip-rule="even
Do we need the `id` attributes that are not used?

Also the border needs to follow like other icons: [video demonstration](https://screenshot.click/05-38-bz5z6-aqu3p.mp4)

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-dankort"><title id="pi-dankort">Dankort</title><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#FFF" d="M36 24H2c-1.333 0-2-.7-2-2V2C0 .667.7 0 2 0h34c1.333 0 2 .7 2 2v20c0 1.333-.667 2-2 2z"/><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="3" stroke-opacity=".07" d="M36 24c1.333 0 2-.7 2-2V2c0-1.333-.7-2-2-2H2C.7 0 0 .7 0 2v20c0 1.333.7 2 2 2h34z"/></g><path fill-rule="evenodd" clip-rule="evenodd" fill="#E31F28" d="M14.7 10.6c.3.267.384.633.25 1.1-.167.633-.383 1.066-.65 1.3-.333.267-.833.4-1.5.4H8.2l1.15-3.15h4.199c.535 0 .918.117 1.151.35zm5.7 1.85L23.95 17h6.95a8.363 8.363 0 01-2.75 2.2c-1.1.533-2.284.8-3.55.8H11.601c-1.2 0-2.351-.267-3.45-.8A7.727 7.727 0 015.4 17h8.1c2.033 0 3.601-.384 4.7-1.15 1.133-.7 1.866-1.833 2.2-3.4zM24.6 4c1.2 0 2.334.267 3.4.8a7.924 7.924 0 012.7 2h-6.75l-3.4 3.5c-.133-1.233-.733-2.133-1.8-2.7-.967-.533-2.316-.8-4.05-.8H5.55a7.82 7.82 0 012.75-2c1.067-.533 2.167-.8 3.301-.8H24.6zM31 7.25c.5.667.9 1.4 1.2 2.2.267.833.4 1.683.4 2.55 0 .833-.133 1.65-.399 2.45-.2.767-.55 1.45-1.05 2.05l-4.25-5.1L31 7.25z"/></svg>
```

2021-03-05 15:44 UTC, tauthomas01 commented on app/assets/images/payment_icons/mobilepay.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-mobilepay"><title id="pi-mobilepay">MobilePay</title><g fill-rule="evenodd" clip-rule
Same comments applied here: unused `id` attributes and border needs to follow other icons.

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-mobilepay"><title id="pi-mobilepay">MobilePay</title><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#FFF" d="M36 24H2c-1.333 0-2-.7-2-2V2C0 .667.7 0 2 0h34c1.333 0 2 .7 2 2v20c0 1.333-.667 2-2 2z"/><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="3" stroke-opacity=".07" d="M36 24c1.333 0 2-.7 2-2V2c0-1.333-.7-2-2-2H2C.7 0 0 .7 0 2v20c0 1.333.7 2 2 2h34z"/></g><path fill-rule="evenodd" clip-rule="evenodd" fill="#5A78FF" d="M24.85 9.2c.601.133 1.134.35 1.601.65v4.8c-1.167-.634-2.434-.917-3.8-.851l1 2.3a1.28 1.28 0 010 1.101c-.167.3-.417.533-.75.7l-4.851 2a1.35 1.35 0 01-.5.1c-.3 0-.55-.066-.75-.2-.233-.133-.417-.35-.55-.649L11.65 7.9c-.133-.3-.133-.633 0-1s.383-.617.75-.75l4.85-2.05a1.303 1.303 0 011 0c.333.167.583.417.75.75l1.05 2.65c1.467-.567 2.75-.783 3.851-.65l.949 2.35zm-2.95 4.6c-1.334.033-2.467.316-3.4.851L16.55 9.9a.525.525 0 00.1-.2c.033-.034.067-.05.1-.05l.1-.1a.596.596 0 00.1-.15c.733-.7 1.55-1.25 2.45-1.65l-1.05-2.6c-.067-.1-.15-.2-.25-.3a.8.8 0 00-.35-.1c-.033 0-.117.017-.25.05l-4.85 2a.888.888 0 00-.35.35c-.033.2-.033.367 0 .5l4.65 11.25a.604.604 0 00.35.35.681.681 0 00.45-.05l4.9-2c.133-.033.25-.15.35-.351a.532.532 0 000-.449l-1.1-2.6z"/></svg>
```

2021-03-05 15:44 UTC, tauthomas01 commented on app/assets/images/payment_icons/ratepay.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-ratepay"><title id="pi-ratepay">RatePay</title><g fill-rule="evenodd" clip-rule="even
Same comments applied here: unused `id` attributes and border needs to follow other icons.

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-ratepay"><title id="pi-ratepay">RatePay</title><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#FFF" d="M36 24H2c-1.333 0-2-.7-2-2V2C0 .667.7 0 2 0h34c1.333 0 2 .7 2 2v20c0 1.333-.667 2-2 2z"/><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="3" stroke-opacity=".07" d="M36 24c1.333 0 2-.7 2-2V2c0-1.333-.7-2-2-2H2C.7 0 0 .7 0 2v20c0 1.333.7 2 2 2h34z"/></g><path fill-rule="evenodd" clip-rule="evenodd" fill="#E4003E" d="M14.2 5.3c1.3-.833 2.75-1.267 4.35-1.3 1.467 0 2.851.367 4.15 1.1l-7.35 7.55L11.4 8.8a8.01 8.01 0 012.8-3.5zm11.7 3.5c.466.967.699 2 .699 3.1 0 2.234-.75 4.133-2.25 5.7-1.566 1.534-3.449 2.334-5.649 2.4-1.066 0-2.116-.2-3.15-.6L25.9 8.8z"/></svg>
```

2021-03-05 15:44 UTC, tauthomas01 commented on app/assets/images/payment_icons/swish.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-swish"><title id="pi-swish">Swish</title><g fill-rule="evenodd" clip-rule="evenodd" i
Same comments applied here: unused id attributes and border needs to follow other icons.

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-swish"><title id="pi-swish">Swish</title><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#FFF" d="M36 24H2c-1.333 0-2-.7-2-2V2C0 .667.7 0 2 0h34c1.333 0 2 .7 2 2v20c0 1.333-.667 2-2 2z"/><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="3" stroke-opacity=".07" d="M36 24c1.333 0 2-.7 2-2V2c0-1.333-.7-2-2-2H2C.7 0 0 .7 0 2v20c0 1.333.7 2 2 2h34z"/></g><g><radialGradient id="pi-swish-SVGID_1_" cx="22.9" cy="8.5" r="12.988" gradientTransform="matrix(1 0 0 1.001 0 -.008)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fdd626"/><stop offset=".314" stop-color="#eb5253"/><stop offset=".506" stop-color="#eb4f65"/><stop offset=".639" stop-color="#e739cb"/><stop offset=".8" stop-color="#9e16ec"/><stop offset="1" stop-color="#5702f0"/></radialGradient><path fill-rule="evenodd" clip-rule="evenodd" fill="url(#pi-swish-SVGID_1_)" d="M22.25 7.95c.566.333 1.1.767 1.6 1.3 1.233 1.233 1.983 2.7 2.25 4.4.034.233.051.449.051.649.033.2.05.384.05.55 0 .267-.017.551-.05.851-.4.7-.9 1.35-1.5 1.95C23.083 19.217 21.2 20 19 20c-1.1 0-2.133-.2-3.1-.6.667.233 1.367.35 2.1.35 1.866 0 3.434-.634 4.7-1.9.434-.466.8-.949 1.1-1.449.033-.067.066-.134.101-.2.533-.934.8-1.95.8-3.05 0-1.867-.667-3.45-2-4.75l-.451-.451z"/><radialGradient id="pi-swish-SVGID_2_" cx="23.45" cy="7.2" r="8.925" gradientTransform="matrix(1 0 0 1.0014 0 -.01)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fdd626"/><stop offset=".365" stop-color="#f17345"/><stop offset=".663" stop-color="#f00912"/><stop offset=".878" stop-color="#ee0920"/><stop offset="1" stop-color="#e30767"/></radialGradient><path fill-rule="evenodd" clip-rule="evenodd" fill="url(#pi-swish-SVGID_2_)" d="M26.15 15.7c.033-.3.05-.584.05-.851 0-.166-.017-.35-.05-.55 0-.2-.017-.416-.051-.649-.267-1.7-1.017-3.167-2.25-4.4a7.206 7.206 0 00-1.6-1.3L24 5.8c.2.167.417.35.65.55a7.173 7.173 0 011.5 2c.567 1.1.85 2.317.85 3.65 0 .4-.017.8-.05 1.2-.167.866-.433 1.7-.8 2.5z"/><radialGradient id="pi-swish-SVGID_3_" cx="14.8" cy="16.8" r="9.25" gradientTransform="matrix(1 0 0 1.0014 0 -.023)" gradientUnits="userSpaceOnUse"><stop offset=".086" stop-color="#424ee9"/><stop offset=".447" stop-color="#58c9be"/><stop offset=".71" stop-color="#59cab5"/><stop offset="1" stop-color="#8ce785"/></radialGradient><path fill-rule="evenodd" clip-rule="evenodd" fill="url(#pi-swish-SVGID_3_)" d="M12.1 7.95c-.067.433-.1.867-.1 1.3v.6c0 .1.017.217.05.35.167 1.767.934 3.333 2.3 4.7.433.466.9.85 1.4 1.149l-1.8 2.2c-.2-.167-.4-.366-.6-.6a7.73 7.73 0 01-1.3-1.7C11.35 14.783 11 13.467 11 12c0-.233.017-.483.05-.75.1-1.2.45-2.3 1.05-3.3z"/><radialGradient id="pi-swish-SVGID_4_" cx="14.65" cy="14.95" r="12.813" gradientTransform="matrix(1 0 0 1.001 0 -.015)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#424ee9"/><stop offset=".392" stop-color="#58c9be"/><stop offset=".765" stop-color="#6cd82e"/><stop offset="1" stop-color="#e5db2a"/></radialGradient><path fill-rule="evenodd" clip-rule="evenodd" fill="url(#pi-swish-SVGID_4_)" d="M15.75 16.05c-.5-.3-.967-.684-1.4-1.149-1.367-1.367-2.133-2.934-2.3-4.7A1.499 1.499 0 0112 9.85v-.6c0-.433.033-.867.1-1.3a7.98 7.98 0 011.25-1.6C14.917 4.783 16.8 4 19 4c1.233 0 2.35.233 3.35.7-.7-.233-1.484-.35-2.35-.35-1.8 0-3.367.633-4.7 1.9a5.93 5.93 0 00-1.05 1.4c-.067.133-.15.25-.25.35-.4.9-.6 1.883-.6 2.95 0 1.833.633 3.399 1.9 4.7.133.133.283.267.45.4z"/></g></svg>
```

2021-03-05 15:44 UTC, tauthomas01 commented on app/assets/images/payment_icons/vipps.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-vipps"><title id="pi-vipps">Vipps</title><g fill-rule="evenodd" clip-rule="evenodd" i
Same comments applied here: unused id attributes and border needs to follow other icons.

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-vipps"><title id="pi-vipps">Vipps</title><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#FFF" d="M36 24H2c-1.333 0-2-.7-2-2V2C0 .667.7 0 2 0h34c1.333 0 2 .7 2 2v20c0 1.333-.667 2-2 2z"/><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="3" stroke-opacity=".07" d="M36 24c1.333 0 2-.7 2-2V2c0-1.333-.7-2-2-2H2C.7 0 0 .7 0 2v20c0 1.333.7 2 2 2h34z"/></g><path fill-rule="evenodd" clip-rule="evenodd" fill="#FF5B24" d="M25.1 6.4c0 .7-.25 1.3-.75 1.8a2.59 2.59 0 01-1.75.65c-.666 0-1.216-.217-1.649-.65-.5-.5-.75-1.1-.75-1.8 0-.733.25-1.316.75-1.75.433-.433.983-.65 1.649-.65.667 0 1.25.217 1.75.65.5.5.75 1.083.75 1.75zm3.5 5.65c.4.367.6.816.6 1.35.066.533-.134 1.083-.601 1.649-2.533 3.3-5.566 4.95-9.1 4.95-2.067 0-3.983-.566-5.75-1.7-1.733-1-3.25-2.533-4.55-4.6-.333-.467-.467-.967-.4-1.5.067-.5.3-.883.7-1.15.4-.3.867-.383 1.4-.25s.967.467 1.3 1c.933 1.4 1.983 2.5 3.15 3.3 1.3.801 2.683 1.2 4.15 1.2 1.366 0 2.583-.3 3.65-.899.833-.534 1.716-1.4 2.649-2.601.4-.6.867-.933 1.4-1 .535-.132 1.002-.049 1.402.251z"/></svg>
```

2021-03-08 06:10 UTC, maunaw commented
@tauthomas01 Thank you. Suggested changes are committed to this PR.  Request you to please review.

2021-03-08 14:39 UTC, tauthomas01 requested changes
Hi,

I left some comments.

Please let me know if there are any questions.

2021-03-08 14:39 UTC, tauthomas01 commented on app/assets/images/payment_icons/dankort.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-dankort"><title id="pi-dankort">Dankort</title><g fill-rule="evenodd" clip-rule="even
The border style needs to follow like other icons

Please follow the [contributions](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) guideline

You can follow this [example icon](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/visa.svg) as a reference.

[![alt](https://screenshot.click/08-27-905oy-bwpi1.png)](https://screenshot.click/08-27-905oy-bwpi1.png)

2021-03-08 14:39 UTC, tauthomas01 commented on app/assets/images/payment_icons/mobilepay.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-mobilepay"><title id="pi-mobilepay">MobilePay</title><g fill-rule="evenodd" clip-rule
Same comment applied here.

2021-03-08 14:39 UTC, tauthomas01 commented on app/assets/images/payment_icons/ratepay.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-ratepay"><title id="pi-ratepay">RatePay</title><g fill-rule="evenodd" clip-rule="even
Same comment applied here.

2021-03-08 14:39 UTC, tauthomas01 commented on app/assets/images/payment_icons/swish.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-swish"><title id="pi-swish">Swish</title><g fill-rule="evenodd" clip-rule="evenodd"><
Same comment applied here.

2021-03-08 14:39 UTC, tauthomas01 commented on app/assets/images/payment_icons/vipps.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" viewBox="0 0 38 24" role="img" aria-labelledby="pi-vipps"><title id="pi-vipps">Vipps</title><g fill-rule="evenodd" clip-rule="evenodd"><
Same comment applied here.

2021-03-24 09:49 UTC, nrbar commented
We have updated the icons. Request you to please review the updated icons with latest commit. Kindly let us know if anything. Thank you.

2021-03-26 07:41 UTC, larouxn requested changes

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/visa.svg
> +</svg>
Can we please remove these changes to `visa.svg`?

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/paypal.svg
> +</svg>
Can we please remove these changes to `paypal.svg`?

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/mastercard.svg
> +</svg>
Can we please remove this duplicate `mastercard.svg`? (already one under `master.svg`)

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/maestro.svg
> +</svg>
Can we please remove these changes to `maestro.svg`?

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/afterpay.svg
> +</svg>
Can we please remove these changes to `afterpay.svg`?
<img width="262" alt="Screen Shot 2021-03-26 at 16 35 56" src="https://user-images.githubusercontent.com/1557529/112598051-613fd300-8e51-11eb-9801-0dac1424f067.png">
<img width="85" alt="Screen Shot 2021-03-26 at 16 36 00" src="https://user-images.githubusercontent.com/1557529/112598054-63099680-8e51-11eb-885a-405ba507d4cc.png">
Source: https://www.afterpay.com/index

2021-03-26 07:41 UTC, larouxn commented on app/assets/images/payment_icons/mobilepay.svg
> +</svg>
May be able to drop this change in favour of https://github.com/activemerchant/payment_icons/pull/424.

2021-05-07 06:36 UTC, maunaw commented
Closing this pull request as created a new one with exact changes required.

2021-05-07 06:36 UTC, closed without merging