Indonesia payment method
activemerchant/payment_icons pull request #425
Opened 2021-03-22 07:28 UTC by candrasaputra

** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

2021-03-22 13:57 UTC, tauthomas01 requested changes
Hi @candrasaputra,

We are no longer accepting icons that are using `base64` because it's [too heavy](https://github.com/activemerchant/payment_icons/issues/407).

Do you have by any chance the SVG files with proper semantics? (`<path>`, `<rect>`, `<circle>`...)

2021-03-24 04:24 UTC, candrasaputra commented
@tauthomas01 not yet, but we work on it.

2021-03-24 08:50 UTC, candrasaputra commented
@tauthomas01 i has update the payment icon, please help to review. thank you.

2021-03-24 13:40 UTC, tauthomas01 requested changes
Hi @candrasaputra ,

Thank you for the fixes, the SVG looks very good now 👍 

On every icons, can we remove the extra white background (`<path xmlns="http://www.w3.org/2000/svg" fill="#fff" d="M0 0h38v24H0z"/>`)? We're not seeing the grey border.

2021-03-24 13:40 UTC, tauthomas01 commented on app/assets/images/payment_icons/bri_direct_debit.svg
> +<svg role="img" width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-bri_direct_debit" xmlns="http://www.w3.org/2000/svg"><title id="pi-bri_direct_debit">BRI Direct Debit</title><path d="M3
Can we remove the extra white background (`<path xmlns="http://www.w3.org/2000/svg" fill="#fff" d="M0 0h38v24H0z"/>`)? We're not seeing the grey border

[Video demonstration](https://screenshot.click/24-18-o5kep-pvgd8.mp4)

2021-03-25 07:57 UTC, candrasaputra commented
@tauthomas01 done

2021-03-25 13:50 UTC, tauthomas01 approved these changes
Looks good.
Thank you for the changes

2021-03-25 14:00 UTC, merged

2021-03-26 01:04 UTC, candrasaputra commented
@tauthomas01 thanks.

could i know, when i can using this icon in shopify?

2021-03-26 01:49 UTC, larouxn commented
👋 @candrasaputra, I'd estimate the icon will be live by end of next week.

2021-03-26 03:14 UTC, candrasaputra commented
@larouxn cool, thanks.