Wcbranch
activemerchant/payment_icons pull request #451
Opened 2021-05-26 06:03 UTC by archerv-windcave

** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.

If this pull request is not adding new icons, you can remove this checklist.

2021-05-26 06:05 UTC, archerv-windcave commented
Farmlands icon request to be added. The logo satisfied all the requirements mentioned in the guidelines.

2021-05-27 02:17 UTC, larouxn commented
👋 Hello @archerv-windcave, it looks like there are some failing tests. You can see them under the [Ruby 3 CI](https://github.com/activemerchant/payment_icons/pull/451/checks?check_run_id=2680956710).

2021-05-27 02:34 UTC, larouxn requested changes

2021-05-27 02:34 UTC, larouxn commented on db/payment_icons.yml
> +  name: farmlands_card
Need to add a `-` above this line like other icons.

2021-05-27 03:05 UTC, larouxn commented
Hmm yeah the UBP test failure is rather strange. We'll definitely want to drop the change (https://github.com/activemerchant/payment_icons/pull/451/commits/1dc4d04c991a2f06d05645d143417d75b37f47ed) from this PR and potentially fix it upstream then rebase here.

Strangely I haven't been able to reproduce the "UBP should be Ubp" error yet.

2021-05-27 03:11 UTC, archerv-windcave commented
I receive another error and I think the name of the card I added does not match with the file and I just change that already. The UBP came back and say expected UBP so I decided to change it back from what it was before. It could also be because of my new card because it sets just above the new added payment logo (I hope).
--
Archer Vallesfin
Software Developer

[Windcave]

T: +6493094693<tel:+6493094693>
D: +6499756273<tel:+6499756273>
E: ***@***.***
W: www.windcave.com
________________________________
WARNING - This email and any attachments may be confidential. If received in error, please delete and inform us by return email. Because emails and attachments may be interfered with, may contain computer viruses or other defects and may not be successfully replicated on other systems, you must be cautious. Windcave cannot guarantee that what you receive is what we sent. If you have any doubts about the authenticity of an email by Windcave, please contact us immediately. It is also important to check for viruses and defects before opening or using attachments. Windcave liability is limited to re-supplying any affected attachments. In addition, no employee of Windcave is authorized to agree upon binding contractual terms such as price via an email message unless such Windcave employee is a senior executive or unless such consent has been approved in writing by a Windcave senior executive. Any representation that violates our policy regarding email consent to contractual terms is null and void.

From: Nicholas La Roux ***@***.***>
Sent: Thursday, 27 May 2021 3:06 PM
To: activemerchant/payment_icons ***@***.***>
Cc: Archer Vallesfin ***@***.***>; Mention ***@***.***>
Subject: Re: [activemerchant/payment_icons] Wcbranch (#451)


Hmm yeah the UBP test failure is rather strange. We'll definitely want to drop the change (1dc4d04<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Factivemerchant%2Fpayment_icons%2Fcommit%2F1dc4d04c991a2f06d05645d143417d75b37f47ed&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7Cf1dcab4786b34a477bee08d920bc5f9c%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637576816507013077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=aYHO6xKA1ROp9MxlUtKCR8wlPS2whASFSRdEn5TSfO4%3D&reserved=0>) from this PR and potentially fix it upstream then rebase here.

Strangely I haven't been able to reproduce the "UBP should be Ubp" error yet.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Factivemerchant%2Fpayment_icons%2Fpull%2F451%23issuecomment-849282440&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7Cf1dcab4786b34a477bee08d920bc5f9c%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637576816507013077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=8PdosCJ696CugcgXLClz1mah34CiLAYm%2Bizlv7zzZ2M%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHFB7ISXH3CFGCADQR6ZBLTPWZILANCNFSM45RCGVMQ&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7Cf1dcab4786b34a477bee08d920bc5f9c%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637576816507023032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=IOMcRyuUDk4qB%2BSn8nQlJnJ0m%2BijF%2Fbx%2FJIqZ9xCti0%3D&reserved=0>.

2021-05-27 03:13 UTC, larouxn commented
```
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:78]:
{:message=>"The 'farmlands' SVG file does not have the appropriate <title> value"}.
Expected: "Farmlands Card"
  Actual: "Farmlands"
```

Hopefully we won't have to worry about UBP at all and can just focus on getting Farmlands Card ready.

2021-05-27 03:18 UTC, archerv-windcave commented
Just make another pull request to fix that. I realize now that the first issue is somewhat related to the yml entry and not from svg itself. I hope it will pass now. Thanks.

--
Archer Vallesfin
Software Developer

[Windcave]

T: +6493094693<tel:+6493094693>
D: +6499756273<tel:+6499756273>
E: ***@***.***
W: www.windcave.com
________________________________
WARNING - This email and any attachments may be confidential. If received in error, please delete and inform us by return email. Because emails and attachments may be interfered with, may contain computer viruses or other defects and may not be successfully replicated on other systems, you must be cautious. Windcave cannot guarantee that what you receive is what we sent. If you have any doubts about the authenticity of an email by Windcave, please contact us immediately. It is also important to check for viruses and defects before opening or using attachments. Windcave liability is limited to re-supplying any affected attachments. In addition, no employee of Windcave is authorized to agree upon binding contractual terms such as price via an email message unless such Windcave employee is a senior executive or unless such consent has been approved in writing by a Windcave senior executive. Any representation that violates our policy regarding email consent to contractual terms is null and void.

From: Nicholas La Roux ***@***.***>
Sent: Thursday, 27 May 2021 3:14 PM
To: activemerchant/payment_icons ***@***.***>
Cc: Archer Vallesfin ***@***.***>; Mention ***@***.***>
Subject: Re: [activemerchant/payment_icons] Wcbranch (#451)


PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:78]:

{:message=>"The 'farmlands' SVG file does not have the appropriate <title> value"}.

Expected: "Farmlands Card"

  Actual: "Farmlands"

Hopefully we won't have to worry about UBP at all and can just focus on getting Farmlands Card ready.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Factivemerchant%2Fpayment_icons%2Fpull%2F451%23issuecomment-849285458&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C25abee9728294a627e7908d920bd7e2e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637576821114277495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YwtkGOTU0Sbcl3hM%2BLyW%2FgDIe6PM7bpy5UR%2FuQwO4Ok%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHFB7ISOVBOTPHS3HNDSVTTPW2HXANCNFSM45RCGVMQ&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C25abee9728294a627e7908d920bd7e2e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637576821114277495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mEMe6fVaBNccKInx1h1%2FavjApBR32X1cC7vI%2FkBdxCA%3D&reserved=0>.

2021-05-27 03:19 UTC, larouxn commented
Yeah, I'll handle UBP if we need to do something. Seems to be alright actually.

Looks like CI passed now! 🙌 
<img width="234" alt="Screen Shot 2021-05-27 at 12 18 51" src="https://user-images.githubusercontent.com/1557529/119760839-b9dd2c00-bee5-11eb-9c28-a4f0d5f79af7.png">

2021-05-27 09:11 UTC, larouxn submitted a review, later dismissed
Seems good to me. 🎩 
<img width="223" alt="Screen Shot 2021-05-27 at 18 10 42" src="https://user-images.githubusercontent.com/1557529/119799306-e8272f80-bf16-11eb-8d52-58ba18757c69.png">

2021-05-28 13:04 UTC, tauthomas01 requested changes

2021-05-28 13:04 UTC, tauthomas01 commented on app/assets/images/payment_icons/farmlands.svg
> +<svg role="img" width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-farmlands" version="1.1" id="pi-svg5448" xmlns="http://www.w3.org/2000/svg"><title id="pi-farmlands">Farmlands Card</tit
Do we need those id attributes?

- `id="pi-g258"` 
- `id="pi-g245"`
- `id="pi-path239"`
- `id="pi-path241"`
- `id="pi-path243"`
- `id="pi-path5444"`
- `id="pi-path5442"`
- `id="pi-svg5448"`

2021-05-30 21:34 UTC, archerv-windcave commented
Hi,

I don't need those attributes. It's alright if removed.

--
Archer Vallesfin
Software Developer

[Windcave]

T: +6493094693<tel:+6493094693>
D: +6499756273<tel:+6499756273>
E: ***@***.***
W: www.windcave.com
________________________________
WARNING - This email and any attachments may be confidential. If received in error, please delete and inform us by return email. Because emails and attachments may be interfered with, may contain computer viruses or other defects and may not be successfully replicated on other systems, you must be cautious. Windcave cannot guarantee that what you receive is what we sent. If you have any doubts about the authenticity of an email by Windcave, please contact us immediately. It is also important to check for viruses and defects before opening or using attachments. Windcave liability is limited to re-supplying any affected attachments. In addition, no employee of Windcave is authorized to agree upon binding contractual terms such as price via an email message unless such Windcave employee is a senior executive or unless such consent has been approved in writing by a Windcave senior executive. Any representation that violates our policy regarding email consent to contractual terms is null and void.

From: tauthomas01 ***@***.***>
Sent: Saturday, 29 May 2021 1:05 AM
To: activemerchant/payment_icons ***@***.***>
Cc: Archer Vallesfin ***@***.***>; Mention ***@***.***>
Subject: Re: [activemerchant/payment_icons] Wcbranch (#451)


@tauthomas01 requested changes on this pull request.

________________________________

In app/assets/images/payment_icons/farmlands.svg<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Factivemerchant%2Fpayment_icons%2Fpull%2F451%23discussion_r641530621&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C806a98b30f34481947c908d921d92926%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637578039509899817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=BjE6IeYMeZnUYByENk3RI2PlTr%2FSUP7o3NbJ8cyyiOY%3D&reserved=0>:

> @@ -0,0 +1 @@

+<svg role="img" width="38" height="24" viewBox="0 0 38 24" aria-labelledby="pi-farmlands" version="1.1" id="pi-svg5448" xmlns="http://www.w3.org/2000/svg"><title id="pi-farmlands">Farmlands Card</title><path d="M35 0H3a3 3 0 00-3 3v18a3 3 0 003 3h32a3 3 0 003-3V3a3 3 0 00-3-3z" opacity=".07" style="isolation:isolate" id="pi-path5442"/><path d="M35 1a2 2 0 012 2v18a2 2 0 01-2 2H3a2 2 0 01-2-2V3a2 2 0 012-2h32" fill="#fff" id="pi-path5444"/><g id="pi-g258" transform="matrix(.07536 0 0 .0841 -12.822 -15.474)" display="inline"><path d="M202.06 422.82c-2.11 0-4.05-.33-5.81-.98-1.76-.65-3.28-1.64-4.54-2.96-1.27-1.32-2.25-2.99-2.95-5-.7-2.01-1.05-4.38-1.05-7.09 0-2.7.36-5.03 1.09-7 .72-1.96 1.69-3.62 2.9-4.95 1.21-1.34 2.72-2.37 4.53-3.1 1.81-.72 3.75-1.09 5.82-1.09 1.69 0 3.32.24 4.89.71 1.57.48 2.97 1.03 4.2 1.65v5.81h-.3c-.37-.31-.84-.67-1.42-1.07s-1.28-.82-2.11-1.24c-.72-.37-1.56-.69-2.53-.96-.97-.28-1.91-.41-2.81-.41-2.68 0-4.83 1.02-6.46 3.05s-2.44 4.9-2.44 8.61c0 3.63.78 6.46 2.35 8.49 1.57 2.03 3.75 3.04 6.54 3.04 1.69 0 3.29-.35 4.82-1.04 1.52-.7 2.87-1.6 4.05-2.7h.3v5.81c-.51.24-1.16.53-1.93.87-.77.34-1.47.59-2.09.76-.88.26-1.67.46-2.37.6-.68.12-1.58.19-2.68.19zm39.1-16.06c0 5.18-1.25 9.18-3.75 11.99-2.5 2.82-5.82 4.23-9.97 4.23-4.28 0-7.64-1.46-10.09-4.36-2.45-2.91-3.68-6.86-3.68-11.86 0-5.14 1.26-9.13 3.79-11.98 2.52-2.85 5.85-4.27 9.98-4.27 4.15 0 7.47 1.42 9.97 4.25 2.5 2.85 3.75 6.84 3.75 12zm-5.34 0c0-3.98-.73-6.94-2.18-8.88-1.45-1.94-3.52-2.9-6.2-2.9-2.7 0-4.78.97-6.24 2.9-1.46 1.94-2.19 4.9-2.19 8.88 0 3.86.73 6.78 2.19 8.77 1.46 1.99 3.54 2.99 6.24 2.99 2.66 0 4.72-.98 6.18-2.93 1.47-1.96 2.2-4.9 2.2-8.83zm24.92-.08h-15.53v-4.99h15.53zm31.53.08c0 5.18-1.25 9.17-3.74 11.99-2.5 2.82-5.82 4.23-9.97 4.23-4.28 0-7.64-1.46-10.09-4.36-2.45-2.91-3.68-6.86-3.68-11.86 0-5.14 1.26-9.13 3.79-11.98 2.52-2.85 5.85-4.27 9.98-4.27 4.15 0 7.47 1.42 9.97 4.25 2.49 2.85 3.74 6.84 3.74 12zm-5.34 0c0-3.98-.73-6.94-2.17-8.88-1.45-1.94-3.52-2.9-6.2-2.9-2.7 0-4.78.97-6.24 2.9-1.46 1.94-2.19 4.9-2.19 8.88 0 3.86.73 6.78 2.19 8.77 1.46 1.99 3.54 2.99 6.24 2.99 2.66 0 4.72-.98 6.18-2.93 1.46-1.96 2.19-4.9 2.19-8.83zm36.45-.82c0 5.12-1.23 9.2-3.68 12.24-2.45 3.04-5.55 4.56-9.29 4.56-1.52 0-2.87-.18-4.05-.53-1.17-.35-2.38-.89-3.61-1.62v12.89h-5.18v-42.1h5.18v3.22c1.28-1.16 2.71-2.13 4.28-2.91 1.57-.78 3.28-1.17 5.14-1.17 3.52 0 6.27 1.39 8.25 4.19 1.98 2.78 2.96 6.53 2.96 11.23zm-5.34.57c0-3.51-.56-6.23-1.68-8.16-1.12-1.94-2.94-2.91-5.45-2.91-1.47 0-2.89.33-4.25.98-1.37.65-2.67 1.49-3.9 2.52v17.43c1.36.66 2.52 1.11 3.48 1.35s2.07.36 3.32.36c2.68 0 4.76-.98 6.25-2.95 1.49-1.96 2.23-4.83 2.23-8.62zm24.07 16.33c-4.9 0-8.7-1.38-11.41-4.14-2.71-2.76-4.06-6.69-4.06-11.77 0-5.01 1.31-9 3.94-11.96 2.63-2.97 6.06-4.45 10.3-4.45 1.91 0 3.6.27 5.07.82 1.47.55 2.76 1.42 3.86 2.59 1.1 1.18 1.95 2.61 2.53 4.31.59 1.7.88 3.78.88 6.24v2.81h-21.31c0 3.58.9 6.31 2.7 8.21 1.8 1.89 4.29 2.83 7.46 2.83 1.14 0 2.25-.13 3.35-.38 1.09-.26 2.08-.59 2.96-.99.94-.42 1.73-.83 2.37-1.22.64-.4 1.17-.77 1.6-1.12h.3v5.65c-.6.24-1.36.54-2.26.89-.9.36-1.71.64-2.42.84-1.01.28-1.92.49-2.74.63-.84.14-1.87.21-3.12.21zm6.06-19.52c-.04-1.4-.2-2.6-.5-3.61-.29-1.01-.72-1.86-1.27-2.56a5.775 5.775 0 00-2.33-1.76c-.95-.4-2.12-.61-3.51-.61-1.38 0-2.55.21-3.51.62-.96.41-1.84 1.02-2.63 1.8-.77.81-1.36 1.7-1.76 2.69-.4.98-.66 2.12-.77 3.43zm26.57-6.39h-.28a5.98 5.98 0 00-1.22-.21c-.43-.03-.95-.04-1.56-.04-1.4 0-2.78.3-4.16.91-1.38.6-2.68 1.51-3.91 2.7v21.84h-5.18v-30.76h5.18v4.57c1.89-1.67 3.54-2.85 4.94-3.54 1.4-.69 2.77-1.03 4.09-1.03.53 0 .93.01 1.2.04.27.03.56.07.89.12v5.4zm20.24 21.92c-.42.31-.99.75-1.69 1.31-.71.56-1.39 1.01-2.05 1.33-.92.48-1.8.85-2.66 1.1-.85.26-2.05.39-3.6.39-1.26 0-2.47-.24-3.61-.71a9.306 9.306 0 01-3-2.01c-.83-.84-1.49-1.89-1.98-3.13-.5-1.24-.74-2.55-.74-3.92 0-2.13.45-3.94 1.35-5.44.9-1.5 2.32-2.69 4.27-3.57 1.73-.79 3.76-1.34 6.11-1.64 2.35-.3 4.88-.53 7.6-.68v-.99c0-1.21-.19-2.19-.55-2.93-.37-.74-.88-1.32-1.54-1.72-.66-.42-1.47-.7-2.42-.84s-1.94-.21-2.94-.21c-1.19 0-2.6.18-4.21.54-1.62.36-3.23.88-4.85 1.55h-.3v-5.26c.95-.28 2.32-.58 4.1-.91 1.78-.33 3.54-.5 5.29-.5 2.11 0 3.89.16 5.34.5 1.45.33 2.75.93 3.91 1.79 1.12.85 1.96 1.94 2.51 3.28.55 1.34.83 2.97.83 4.9v21.04H395v-3.27zm0-4.3v-8.54c-1.23.11-2.79.26-4.67.46-1.88.19-3.4.46-4.56.81-1.38.42-2.52 1.07-3.42 1.94-.9.87-1.35 2.09-1.35 3.65 0 1.76.5 3.09 1.49 3.99.99.9 2.44 1.35 4.35 1.35 1.63 0 3.11-.35 4.43-1.06 1.33-.7 2.57-1.57 3.73-2.6zm21.72 8.18c-2.83 0-5.03-.8-6.61-2.41s-2.37-4.15-2.37-7.62v-17.04h-3.5v-4.3h3.5v-8.84h5.18v8.84h9.53v4.3h-9.53v14.62c0 1.56.03 2.76.08 3.61.06.84.27 1.63.63 2.37.31.64.82 1.13 1.51 1.45.7.32 1.64.48 2.84.48.84 0 1.66-.12 2.45-.38.79-.25 1.36-.45 1.71-.62h.3v4.65c-.97.28-1.96.49-2.96.65-.99.16-1.91.24-2.76.24zm15.2-36.51h-5.89v-5.37h5.89zm-.35 35.91h-5.18v-30.76h5.18zm31.77-30.76l-11.59 30.76h-4.66l-11.51-30.76h5.59l8.43 23.73 8.34-23.73zm16.83 31.47c-4.9 0-8.71-1.38-11.41-4.14-2.71-2.76-4.06-6.69-4.06-11.77 0-5.01 1.31-9 3.94-11.96 2.62-2.97 6.06-4.45 10.3-4.45 1.91 0 3.6.27 5.07.82 1.47.55 2.75 1.42 3.85 2.59 1.1 1.18 1.95 2.61 2.53 4.31.59 1.7.88 3.78.88 6.24v2.81h-21.31c0 3.58.9 6.31 2.7 8.21 1.8 1.89 4.29 2.83 7.46 2.83 1.14 0 2.25-.13 3.35-.38 1.09-.26 2.08-.59 2.96-.99.93-.42 1.72-.83 2.37-1.22.64-.4 1.18-.77 1.6-1.12h.3v5.65c-.61.24-1.36.54-2.26.89-.9.36-1.71.64-2.43.84-1.01.28-1.92.49-2.74.63-.82.14-1.86.21-3.1.21zm6.06-19.52c-.04-1.4-.2-2.6-.5-3.61-.29-1.01-.72-1.86-1.27-2.56-.6-.77-1.38-1.36-2.32-1.76-.95-.4-2.12-.61-3.51-.61-1.38 0-2.55.21-3.51.62-.96.41-1.84 1.02-2.63 1.8-.77.81-1.36 1.7-1.76 2.69-.4.98-.66 2.12-.77 3.43z" id="pi-path237" fill="#00553d"/><g id="pi-g245"><path d="M233.21 307.84h-28.29v13.6H231v13.22h-26.08v30.53h-16.83v-70.56h45.12v13.21m34.56 43.35v-11.1c-2.64.26-4.79.52-6.45.7-1.64.24-3.26.62-4.84 1.24-1.38.49-2.45 1.27-3.22 2.28-.77 1.04-1.14 2.41-1.14 4.12 0 2.52.63 4.23 1.9 5.16 1.29.94 3.17 1.41 5.65 1. [...]

2021-05-31 14:51 UTC, tauthomas01 commented
Yes, please remove those attributes.

2021-08-23 23:12 UTC, archerv-windcave commented
Can you please check my changes Thomas. I already removed those unnecessary id's and also the conflict. Thank you.

2021-08-24 09:33 UTC, larouxn commented
Looks like there's a test failure related to the `title` element.
```
Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:78]:
{:message=>"The 'farmland' SVG file does not have the appropriate <title> value"}.
Expected: "Farmland"
  Actual: "Farmlands Card"
```
https://github.com/activemerchant/payment_icons/pull/451/checks?check_run_id=3409558962

2021-08-30 06:44 UTC, larouxn commented
@archerv-windcave, are you alright with the margin spacing difference compared to other icons? If so, we can merge this.

2021-08-30 06:56 UTC, archerv-windcave commented
Hi Nicholas,

I'm okay with the spacing, please merge the icon for us please.

Thank you for your awesome support.

Regards,
--
Archer Vallesfin
Software Developer

[Windcave]

T: +6493094693<tel:+6493094693>
D: +6499756273<tel:+6499756273>
E: ***@***.***
W: www.windcave.com
________________________________
WARNING - This email and any attachments may be confidential. If received in error, please delete and inform us by return email. Because emails and attachments may be interfered with, may contain computer viruses or other defects and may not be successfully replicated on other systems, you must be cautious. Windcave cannot guarantee that what you receive is what we sent. If you have any doubts about the authenticity of an email by Windcave, please contact us immediately. It is also important to check for viruses and defects before opening or using attachments. Windcave liability is limited to re-supplying any affected attachments. In addition, no employee of Windcave is authorized to agree upon binding contractual terms such as price via an email message unless such Windcave employee is a senior executive or unless such consent has been approved in writing by a Windcave senior executive. Any representation that violates our policy regarding email consent to contractual terms is null and void.

From: Nicholas La Roux ***@***.***>
Sent: Monday, 30 August 2021 6:44 PM
To: activemerchant/payment_icons ***@***.***>
Cc: Archer Vallesfin ***@***.***>; Mention ***@***.***>
Subject: Re: [activemerchant/payment_icons] Wcbranch (#451)


@archerv-windcave<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farcherv-windcave&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C45ffdd98f68843df472c08d96b81a23e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637659026785197415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xjYsXbF5WQrqAjtCq%2F357yuLzCEHpzuo9zY448rT4Lg%3D&reserved=0>, are you alright with the margin spacing difference compared to other icons? If so, we can merge this.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Factivemerchant%2Fpayment_icons%2Fpull%2F451%23issuecomment-908076225&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C45ffdd98f68843df472c08d96b81a23e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637659026785207370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6HcvXlPdTkcZS41TXqWRbQyOZ1MamJNrrtgxKkEbTN4%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHFB7M5AIRSCSR46DZZVF3T7MSE3ANCNFSM45RCGVMQ&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C45ffdd98f68843df472c08d96b81a23e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637659026785207370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D8CQAOgLi5CRbJTL7nASpvAKNUsy5eUgwrrNc8U7qDE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C45ffdd98f68843df472c08d96b81a23e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637659026785207370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Gaj7LaJFo1JSsJXDm%2BXsKzQdnwj8HENtFvnX16GvLs%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CArcher.Vallesfin%40windcave.com%7C45ffdd98f68843df472c08d96b81a23e%7Ceeaea23d3b9c48568451b7507fb82199%7C0%7C0%7C637659026785217329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rPDD1Qwrwcr2ZQW0Kn6Y7yrg%2Bqr9DqKVI%2FmTbfoweBE%3D&reserved=0>.

2021-08-30 08:21 UTC, merged

2021-09-13 01:02 UTC, larouxn commented
👋 Just a heads up that we are hoping to have this live across Shopify within the month. Currently waiting on some other icons so we can batch the update. Thank you. 🙇‍♂️

2021-09-30 08:05 UTC, larouxn commented
👋  Ran into a few release pipeline issues. Hoping to have this live by end of next week, potentially sooner.