Svea icons
activemerchant/payment_icons pull request #604
Opened 2022-04-01 11:04 UTC by mgpkauko

** Checklist **
- [x ] All icons have a corresponding entry in `db/payment_icons.yml`
- [x ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x ] I am confident that all icons are clear and easy to read/understand
- [x ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

2022-04-11 05:12 UTC, mgpkauko commented
Updated the image files and restored the tags removed by svgo (regardless of disable -attribute). Should be ok now.

2022-04-21 10:56 UTC, larouxn requested changes

2022-04-21 10:56 UTC, larouxn commented on db/payment_icons.yml
>    group: other
Looks like these entries are missing the preceding `-`. Please see other entries for reference. (or see below)

https://github.com/activemerchant/payment_icons/blob/b2ebb1241bc8bb7da0d2a196c7576696d7a0bfe4/db/payment_icons.yml#L1-L4

2022-04-26 11:35 UTC, larouxn approved these changes
Looks good to me 🎩 
![image](https://user-images.githubusercontent.com/1557529/165291293-72caa5f1-c6e7-4d63-91e5-d6aa391a3aba.png)

(part payment could probably be adjusted a bit margin wise, but it's more or less alright)

2022-04-26 19:16 UTC, tauthomas01 approved these changes

2022-04-27 00:12 UTC, merged

2022-04-28 06:24 UTC, larouxn commented
👋 Hello, your icon(s) should be available everyone now. Please let us know if otherwise.