Adding laybuy icon for new payment app extension
activemerchant/payment_icons pull request #675
Opened 2022-07-06 21:32 UTC by scplaybuy

** Checklist **
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

2022-07-06 21:33 UTC, scplaybuy reviewed
no brand link available - but verified by our marketing people - thanks.

2022-07-07 02:46 UTC, scplaybuy reviewed
updated from first test fail, removed extraneous file

2022-07-07 08:33 UTC, larouxn commented
👋 Can we update the icon to match the rest of the icons (shape)? ([template](https://github.com/activemerchant/payment_icons/blob/bd0f7ce66eef2cac215145d466cc21cb3474e24c/CONTRIBUTING.md#template))
<img width="64" alt="Screen Shot 2022-07-07 at 17 33 25" src="https://user-images.githubusercontent.com/1557529/177729412-c7299bf2-7972-43f7-b107-f50dc01200a1.png">
<img width="245" alt="Screen Shot 2022-07-07 at 17 32 31" src="https://user-images.githubusercontent.com/1557529/177729419-91943960-1b3a-47a3-8433-a41512aefaee.png">

2022-07-08 02:53 UTC, scplaybuy commented
@larouxn Hi Nicholas. I've checked the svg mark up for both visa and heart, and heart seems to be correct. Also in a svg view it appears to be the correct shape and size. opening in a browser probably isn't the best viewport? Can you let me know explicity what you want me to change as I can't see the issue :)

I've updated the image to include that template's example path elements too, if that's what you mean?
thanks,

see attached screen shorts
![Screen Shot 2022-07-08 at 2 42 29 PM](https://user-images.githubusercontent.com/97417655/177906460-f3b24440-d107-41cc-83f0-463d708b7636.png)
![Screen Shot 2022-07-08 at 2 42 41 PM](https://user-images.githubusercontent.com/97417655/177906465-8f7aa0b1-1c69-4ee8-baa3-379f580bacfa.png)

2022-07-12 05:14 UTC, larouxn requested changes
Hello, the icon is still not the correct shape. Maybe we can recreate it using the [template](https://github.com/activemerchant/payment_icons/blob/bd0f7ce66eef2cac215145d466cc21cb3474e24c/CONTRIBUTING.md#template)?
<img width="438" alt="Screen Shot 2022-07-12 at 14 14 29" src="https://user-images.githubusercontent.com/1557529/178413806-568dc570-256b-440c-897b-abbdd3f6ddf1.png">

2022-07-12 22:14 UTC, scplaybuy commented
Hi Nicholas,

Do you mean it's not got rounded corners? other icons have square corners, otherwise I can't see what you mean by not the same shape. I have the same height/width and viewport attributes as the template :)

please let me know explicitly what element of the shape you mean?

thanks,

2022-07-13 23:04 UTC, scplaybuy commented
Have added rounded edges, assuming that's what you meant 👍🏼

2022-07-15 07:34 UTC, larouxn commented
> Do you mean it's not got rounded corners? other icons have square corners, otherwise I can't see what you mean by not the same shape. I have the same height/width and viewport attributes as the template :)

Sorry for any confusion. All icons should look like the Visa icon I posted earlier. Any icon that's square/a different shape, is probably old and/or before we had icon guidelines.

2022-07-18 04:17 UTC, scplaybuy commented
Hi,
I used the template. the only different is the background colour and vectors that create the laybuy shape :)

2022-07-20 12:48 UTC, larouxn commented on db/payment_icons.yml
> +  name: heart
Can we rebase this PR and fix this name? Should be `laybuy`.

2022-07-21 02:12 UTC, scplaybuy commented
ive renamed the old one laybuy-gateway.. and the new one (heart) to laybuy.
I can't see anything in dev note but I assume these names = app name used?

2022-07-21 06:27 UTC, larouxn commented
> ive renamed the old one laybuy-gateway.. and the new one (heart) to laybuy. I can't see anything in dev note but I assume these names = app name used?

Should all places using the old icon start seeing the new icon automatically? If not then maybe we should actually keep the old icon as `laybuy` and change the new one to `laybuy-heart`.

2022-07-21 06:39 UTC, scplaybuy commented
hi,
i really don't know how their icon system joins up - i think now that the gateway is defunct and all merchants should be using the new app (https://partners.shopify.com/616717/apps/5822183/overview#/) - what we want is this icon to appear next to Laybuy when they app is installed and customers see Laybuy as a payment option at checkout.

2022-07-21 06:42 UTC, scplaybuy commented
next to the text Laybuy at checkout: [](url
<img width="684" alt="Screen Shot 2022-07-21 at 6 41 08 PM" src="https://user-images.githubusercontent.com/97417655/180146765-8624d09f-7705-458b-82d4-b21a28323afc.png">
)

2022-07-21 06:58 UTC, larouxn commented
I see now. It looks like `Laybuy` was rebranded from the old icon (currently in this repo) to the new one (added in this PR). In that case, do you want to remove the old icon in this PR too? We can just completely replace the old icon with the new icon.

<img width="500" alt="Screen Shot 2022-07-21 at 15 55 25" src="https://user-images.githubusercontent.com/1557529/180149610-faa5e7ee-6653-4a8b-a402-468d8dc98c6b.png">
<img width="1920" alt="Screen Shot 2022-07-21 at 15 55 32" src="https://user-images.githubusercontent.com/1557529/180149617-48910b50-c8bc-4ad0-9227-f15ce512597f.png">

In summary
- remove old Laybuy icon
- add new Laybuy icon with same name
- update `payment_icons.yml` entry (looks `label` is different now)

2022-07-21 08:19 UTC, scplaybuy commented
Hi Nicolas,
I've checked with our product expert, that older laybuy icon is actually a totally different company.
So, I'll change our one to laybuy-heart if that works for you and push again, reverting the old icon name change.
thanks, simon

2022-07-26 07:05 UTC, larouxn commented
> Hi Nicolas, I've checked with our product expert, that older laybuy icon is actually a totally different company. So, I'll change our one to laybuy_heart if that works for you and push again, reverting the old icon name change. thanks, simon

Oh wow, okay. Interesting. That works for me. Thanks!

2022-07-26 07:11 UTC, larouxn submitted a review, later dismissed
Looks good to me 🎩 
<img width="443" alt="Screen Shot 2022-07-26 at 16 11 06" src="https://user-images.githubusercontent.com/1557529/180945666-2e93c3a6-b235-4a29-a6a4-130cddfb9856.png">

2022-07-26 07:12 UTC, larouxn commented
Need to update the SVG with the new ID: `pi-heart` → `pi-laybuy_heart`. ([CI logs](https://github.com/activemerchant/payment_icons/runs/7515012714?check_suite_focus=true))

```ruby
Failure:
PaymentIconTest#test_Every_payment_SVG_meets_accessibility_requirements [/home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:81]:
{:message=>"The 'laybuy_heart' SVG file does not have the appropriate 'id' value on the <title> tag"}.
Expected: "pi-laybuy_heart"
  Actual: "pi-heart"

rails test /home/runner/work/payment_icons/payment_icons/test/unit/payment_icon_test.rb:61

..........

Finished in 1.057246s, 12.2961 runs/s, 5817.9443 assertions/s.
13 runs, 6[15](https://github.com/activemerchant/payment_icons/runs/7515012714?check_suite_focus=true#step:4:16)1 assertions, 1 failures, 0 errors, 0 skips
```

2022-07-27 08:35 UTC, AlexRohloff commented
Nicholas, Simon is currently on leave. Do you have everything you need here and can we get an ETA on when the logo will be live?

2022-07-27 11:04 UTC, larouxn commented
> Nicholas, Simon is currently on leave. Do you have everything you need here and can we get an ETA on when the logo will be live?

Hey Alex, we need to update the SVG to use `laybuy-heart` for it's IDs re: https://github.com/activemerchant/payment_icons/pull/675#issuecomment-1195096695.

2022-07-27 11:44 UTC, AlexRohloff commented
> > Nicholas, Simon is currently on leave. Do you have everything you need here and can we get an ETA on when the logo will be live?
> 
> Hey Alex, we need to update the SVG to use `laybuy-heart` for it's IDs re: [#675 (comment)](https://github.com/activemerchant/payment_icons/pull/675#issuecomment-1195096695).

Is this something we need to do or managed at your end?

2022-07-28 04:00 UTC, larouxn commented
> > > Nicholas, Simon is currently on leave. Do you have everything you need here and can we get an ETA on when the logo will be live?
> > 
> > 
> > Hey Alex, we need to update the SVG to use `laybuy-heart` for it's IDs re: [#675 (comment)](https://github.com/activemerchant/payment_icons/pull/675#issuecomment-1195096695).
> 
> Is this something we need to do or managed at your end?

Need to do it on your end, here in this PR or CI will continue failing and we won't be able to merge.

https://github.com/activemerchant/payment_icons/runs/7515012714?check_suite_focus=true

2022-08-01 02:47 UTC, scplaybuy commented
@larouxn updated

2022-08-01 04:41 UTC, larouxn approved these changes
Looks good to me 🎩 
<img width="422" alt="Screen Shot 2022-08-01 at 13 40 45" src="https://user-images.githubusercontent.com/1557529/182073745-2fb619ec-7222-40d5-9717-8594fd0d1bce.png">
<img width="431" alt="Screen Shot 2022-08-01 at 13 41 17" src="https://user-images.githubusercontent.com/1557529/182073747-78de22b6-e993-4354-a880-e48f4a1c7741.png">

@tauthomas01, what do you think?

2022-08-03 01:01 UTC, larouxn commented
Hey @scplaybuy, nothing else you need to do on your end. We'll get this merged and released, then I'll comment back here when it's live/ready to be used.

2022-08-08 13:07 UTC, tauthomas01 approved these changes
Looks good

2022-08-09 03:13 UTC, merged

2022-08-09 03:36 UTC, larouxn commented
👋 Hello, we're working on the [v1.7.16](https://github.com/activemerchant/payment_icons/pull/702) release now. It will likely go live next week.

Apologies for the wait. Will report back here when it's live. 🙇‍♂️

2022-08-19 02:22 UTC, todd-lb commented
Kia ora @larouxn, are you able to please provide an update on this please?

2022-08-19 07:19 UTC, larouxn commented
👋 Hello, your new/updated icon(s) should now be live everywhere. ✨

2022-10-11 09:29 UTC, scplaybuy commented
Hi Nicholas,

Do you mean it's not got rounded corners? other icons have square corners,
otherwise I can't see what you mean by not the same shape. I have the same
height/width and viewport attributes as the template :)

please let me know explicitly what element of the shape you mean?

thanks,

Simon


On Tue, 12 Jul 2022 at 17:15, Nicholas La Roux ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello, the icon is still not the correct shape. Maybe we can recreate it
> using the template
> <https://github.com/activemerchant/payment_icons/blob/bd0f7ce66eef2cac215145d466cc21cb3474e24c/CONTRIBUTING.md#template>
> ?
> [image: Screen Shot 2022-07-12 at 14 14 29]
> <https://user-images.githubusercontent.com/1557529/178413806-568dc570-256b-440c-897b-abbdd3f6ddf1.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/activemerchant/payment_icons/pull/675#pullrequestreview-1035221512>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXHHTN2CYQE3JTM5GI6EFDLVTT5NPANCNFSM523GXZEQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>