Multibanco payment icon addition
activemerchant/payment_icons pull request #705
Opened 2022-08-16 17:32 UTC by nehagarg-shopify

** Checklist **
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/) - I have actually reused the icon for mb. Since there was no way to reuse it as alias, I had to create a new entry for Multibanco
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

2022-09-07 18:29 UTC, lunataoo requested changes

2022-09-07 18:29 UTC, lunataoo commented on app/assets/images/payment_icons/multibanco.svg
> +<svg role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-mb" xmlns="http://www.w3.org/2000/svg"><title id="pi-mb">Multibanco</title><path fill="#000" opacity=".07" d="M35 0H3C1.
Can you change the `aria-labelledby="pi-mb"` to `pi-multibanco` as suggested in the [Markup guideline](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#markup)?

2022-09-07 18:29 UTC, lunataoo commented on db/payment_icons.yml
> +  group: other
What's happening to the old multibanco icon? Found it [here](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/mb.svg)

2022-09-16 19:13 UTC, rahilvirani commented
@nehagarg-shopify it looks like that you are making changes to Shopify to use the existing multibanco logo. If so, can you please close this PR

2022-09-19 11:17 UTC, nehagarg-shopify commented
Closing this PR as we are now passing `mb` as the input to this gem for Multibanco.

2022-09-19 11:17 UTC, closed without merging