Atrato icon
activemerchant/payment_icons pull request #826
Opened 2023-02-21 21:44 UTC by diego3799

## Why are you adding this icons?
I'm adding/updating this icon(s) because we are an authorized buy now pay later payment method in shopify

#### Help us identify yourself
- [x] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
<img width="209" alt="Screenshot 2023-02-21 at 15 40 13" src="https://user-images.githubusercontent.com/43474408/220464708-c51343e5-54d2-45c6-9034-7a9fc85e989e.png">

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: black; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg width="38" height="24" viewBox="0 0 38 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="pi-atrato"><title id="pi-atrato">Atrato</title><g clip-path="url(#clip0_275_1735)"><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z" fill="#000"/><path d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32z" fill="#fff"/><path d="M34.615 9h-3.643c-.765 0-1.386.695-1.386 1.552v3.766c0 .857.62 1.552 1.386 1.552h3.643c.765 0 1.385-.695 1.385-1.552v-3.766C36 9.695 35.38 9 34.615 9z" fill="#DED0F9"/><path d="M9.538 13.398v-2.27h1.166v-.84H9.538V9.225H8.46v1.063h-.955v.84h.955v2.438c0 .698.398 1.122 1.113 1.122h1.308v-.875h-.937c-.282 0-.406-.132-.406-.415M12.799 11.26v-.972h-1.052v4.4h1.07v-1.855c0-1.078.406-1.529 1.333-1.529.16 0 .319.01.477.027v-1.096a1.316 1.316 0 00-.291-.027c-.98 0-1.387.698-1.537 1.052M18.958 13.575v-1.776c0-1.078-.663-1.644-1.874-1.644-1.21 0-1.926.645-2.024 1.3l.981.255c.116-.389.39-.742 1.043-.742.566 0 .805.265.805.698v.15c-1.441.133-2.766.512-2.766 1.74 0 .779.583 1.264 1.405 1.264.742 0 1.21-.37 1.476-.786.052.389.247.654.804.654h.822v-.849h-.407c-.23 0-.265-.052-.265-.264m-1.07-.698c0 .786-.494 1.13-1.007 1.13-.441 0-.662-.212-.662-.548 0-.636.769-.839 1.67-.936v.354zM21.794 13.398v-2.27h1.166v-.84h-1.166V9.225h-1.078v1.063h-.955v.84h.955v2.438c0 .698.397 1.122 1.113 1.122h1.308v-.875H22.2c-.282 0-.406-.132-.406-.415M25.85 10.155c-1.29 0-2.227.954-2.227 2.333 0 1.379.945 2.333 2.227 2.333 1.28 0 2.217-.937 2.217-2.333 0-1.396-.927-2.333-2.217-2.333m0 3.791c-.654 0-1.105-.468-1.105-1.44 0-.973.45-1.476 1.105-1.476.653 0 1.095.495 1.095 1.476 0 .98-.45 1.44-1.095 1.44zM4.084 9.225L2 14.688h1.217l.458-1.269h2.226l.447 1.27H7.58L5.511 9.224H4.084zm-.085 3.298l.802-2.22.783 2.22H4zM32.788 14.466c-.604 0-1.09-.184-1.486-.564-.396-.38-.588-.848-.588-1.434v-.033c.005-.337.076-.645.211-.915l.788.461a1.43 1.43 0 00-.08.45v.037c0 .343.106.627.318.847.211.226.492.342.831.342.34 0 .628-.109.845-.323.213-.215.321-.506.321-.866v-.033a1.36 1.36 0 00-.084-.455l.787-.461c.138.268.21.576.215.918 0 .015 0 .032.005.05-.004.576-.195 1.039-.582 1.415-.391.38-.883.565-1.502.565M32.203 11.519h-.127a.326.326 0 01-.326-.326v-.287c0-.18.146-.326.326-.326h.127c.18 0 .325.146.325.326v.287c0 .18-.145.326-.325.326zM33.511 11.519h-.127a.326.326 0 01-.325-.326v-.287c0-.18.146-.326.326-.326h.126c.18 0 .326.146.326.326v.287c0 .18-.146.326-.326.326z" fill="#000"/></g><defs><clipPath id="clip0_275_1735"><path fill="#fff" d="M0 0h38v24H0z"/></clipPath></defs></svg>

<br>

</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?
As soon as possible because as I said before we are already approved as a buy now pay later payment method

2023-02-22 21:37 UTC, Jacquesattaque requested changes
@diego3799 The icon looks good, but the logo is a bit tight to the border. Can you increase the space to the left and right and re-submit? You've also got some automated checks to clear.

2023-02-27 17:06 UTC, diego3799 commented
All conflicts and test have been updated! Thanks for the review!

2023-03-01 14:42 UTC, Jacquesattaque commented
@diego3799 You still have some automated checks failing. Once those are clear I can approve.

2023-03-03 19:52 UTC, Jacquesattaque approved these changes

2023-03-10 09:17 UTC, merged