Cetelem icon
activemerchant/payment_icons pull request #847
Opened 2023-03-11 12:58 UTC by kiwopdev

## Why are you adding this icons?
I'm adding this icon(s) because we created a new Payment APP for Shopify with Cetelem

#### Help us identify yourself
- I'm the developer of the APP Payment of the brand (Cetelem) directly and they have provided the icons.

## Checklist to add new icons
- [X] All icons have a corresponding entry in `db/payment_icons.yml`
- [X] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [X] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [X] I am confident that all icons are clear and easy to read/understand
- [X] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [X] I have attached a screenshot comparison with the example icon provided in guidelines
- [X] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

## Attach a screenshot of the icon along side the example Visa icon

![Screenshot 2023-03-11 at 13 58 04](https://user-images.githubusercontent.com/79518096/224485912-5b692252-19b0-4d34-8db8-7a1f16215c87.jpg)

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" width="38" height="24" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="pi-cetelem"><title id="pi-cetelem">Cetelem</title><path d="m35 0h-32c-1.7 0-3 1.3-3 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3v-18c0-1.7-1.4-3-3-3z" opacity=".07"/><path d="m35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2h-32c-1.1 0-2-.9-2-2v-18c0-1.1.9-2 2-2z" fill="#fff"/><g fill="#3a9044" transform="matrix(.1 0 0 -.1 0 512)"><path d="m185.7 5093.5c-24.8-1.9-46.9-17-57.9-39.7-13.1-27-7.8-59.2 13.2-80.5 13.5-13.7 31.2-21 50.4-21 10.5 0 19.1 1.8 28.7 6 8.8 3.8 20 12 23.1 16.9 3.4 5.4 2.7 12.3-1.9 16.8-1 1-2.7 2.2-3.9 2.8-1.8.8-2.6 1-5.4 1-4.3 0-6.4-1-10.7-4.7-8.9-7.9-18.6-11.7-30-11.7-11.5 0-21.8 4.1-30.2 12.1-3.7 3.6-6.1 6.7-8.4 11.2-3.5 6.8-5 12.8-5 20.4 0 9 2.3 16.5 7.1 24 2.2 3.4 7 8.5 10.4 11 3.3 2.6 10.5 6 15 7.2 3.4.9 4.3 1 10.9 1 6.2 0 7.7-.1 10.4-.8 7.9-2 13.8-5.2 20.7-11.4 4.4-3.9 8.7-5.1 13.5-3.5 9.8 3 12.8 14.6 5.8 22.2-1.1 1.2-3.5 3.4-5.4 4.9-11.6 9.4-24.8 14.6-39.8 15.8-2.7.2-5.4.3-5.9.3s-2.6-.1-4.7-.3z"/><path d="m138.6 4930.5c-3.5-.9-6.4-3.2-8.1-6.5-1.1-2.2-1.2-2.8-1.2-5.4 0-2.4.2-3.3 1-5 1.1-2.4 3.3-4.8 5.4-5.8 3.1-1.6 3.7-1.6 54.3-1.4l48.4.1 2.2 1c8.2 3.8 9.9 14.2 3.3 20.2-3.8 3.5 1.1 3.2-54.7 3.3-28.1-.2-49.8-.4-50.6-.5z"/></g></svg>

<br>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" width="38" height="24" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="pi-cetelem"><title id="pi-cetelem">Cetelem</title><path d="m35 0h-32c-1.7 0-3 1.3-3 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3v-18c0-1.7-1.4-3-3-3z" opacity=".07"/><path d="m35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2h-32c-1.1 0-2-.9-2-2v-18c0-1.1.9-2 2-2z" fill="#fff"/><g fill="#3a9044" transform="matrix(.1 0 0 -.1 0 512)"><path d="m185.7 5093.5c-24.8-1.9-46.9-17-57.9-39.7-13.1-27-7.8-59.2 13.2-80.5 13.5-13.7 31.2-21 50.4-21 10.5 0 19.1 1.8 28.7 6 8.8 3.8 20 12 23.1 16.9 3.4 5.4 2.7 12.3-1.9 16.8-1 1-2.7 2.2-3.9 2.8-1.8.8-2.6 1-5.4 1-4.3 0-6.4-1-10.7-4.7-8.9-7.9-18.6-11.7-30-11.7-11.5 0-21.8 4.1-30.2 12.1-3.7 3.6-6.1 6.7-8.4 11.2-3.5 6.8-5 12.8-5 20.4 0 9 2.3 16.5 7.1 24 2.2 3.4 7 8.5 10.4 11 3.3 2.6 10.5 6 15 7.2 3.4.9 4.3 1 10.9 1 6.2 0 7.7-.1 10.4-.8 7.9-2 13.8-5.2 20.7-11.4 4.4-3.9 8.7-5.1 13.5-3.5 9.8 3 12.8 14.6 5.8 22.2-1.1 1.2-3.5 3.4-5.4 4.9-11.6 9.4-24.8 14.6-39.8 15.8-2.7.2-5.4.3-5.9.3s-2.6-.1-4.7-.3z"/><path d="m138.6 4930.5c-3.5-.9-6.4-3.2-8.1-6.5-1.1-2.2-1.2-2.8-1.2-5.4 0-2.4.2-3.3 1-5 1.1-2.4 3.3-4.8 5.4-5.8 3.1-1.6 3.7-1.6 54.3-1.4l48.4.1 2.2 1c8.2 3.8 9.9 14.2 3.3 20.2-3.8 3.5 1.1 3.2-54.7 3.3-28.1-.2-49.8-.4-50.6-.5z"/></g></svg>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify? As soon as possible

2023-03-14 15:55 UTC, Jacquesattaque commented
@kiwopdev The SVG isn't showing up in the PR. Can you re-upload please?

2023-03-14 17:19 UTC, Jacquesattaque requested changes
Looks like you have some automated checks failing. I would recommend adding another pixel or two of padding between the logo and the border of the icon as well. It looks really tight compared to most icons in our library.

2023-03-15 18:12 UTC, kiwopdev commented
@Jacquesattaque Done! Let me know if we need anything else

2023-03-15 20:04 UTC, Jacquesattaque approved these changes

2023-04-05 12:40 UTC, merged