Yoco instant eft
activemerchant/payment_icons pull request #879
Opened 2023-06-14 14:09 UTC by jasonatyoco

## Why are you adding this icons?
I'm adding/updating this icon(s) because our Yoco payment app now supports instant eft, and we would like to reflect that in the app with an icon

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: black; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<YOUR SVG CODE>

<br>
<svg xmlns="http://www.w3.org/2000/svg" width="38" height="24" fill="none"><path fill="#fff" d="M0 0h38v24H0z"/><path fill="#000" d="M11.039 9v-.724h.9V6.384h-.9v-.692h2.537v.692h-.9v1.892h.9V9H11.04Zm3.88-2.315V9h-.75V5.692h.778l2.01 2.246.027.041V5.692h.747V9h-.747l-2.032-2.268-.032-.047Zm5.237 2.412c-.436 0-.789-.041-1.067-.134-.552-.181-.83-.548-.947-1.137h.845c.111.46.524.594 1.187.594.608 0 .882-.116.882-.39 0-.106-.037-.185-.107-.227-.148-.097-.487-.12-1.164-.158a3.508 3.508 0 0 1-.835-.13c-.441-.13-.65-.394-.65-.858 0-.64.543-1.048 1.624-1.048 1.15 0 1.763.32 1.916 1.155h-.83c-.093-.422-.474-.506-1.1-.506-.622 0-.821.14-.821.376 0 .116.032.195.18.25.145.056.414.093.878.112a4.5 4.5 0 0 1 .97.13c.505.134.723.394.723.849 0 .71-.52 1.122-1.684 1.122Zm3.902-2.741V9h-.797V6.356h-1.188v-.664h3.229v.664h-1.244Zm3.609 1.925h-1.833L25.491 9h-.84l1.675-3.308h.821L28.85 9h-.83l-.353-.719Zm-.933-1.888-.598 1.257h1.216l-.617-1.257Zm3.24.292V9h-.752V5.692h.78l2.008 2.246.028.041V5.692h.747V9h-.747l-2.032-2.268-.032-.047Zm5.324-.33V9H34.5V6.356h-1.188v-.664h3.23v.664h-1.244ZM18.9 17.826h-8.003v-8.13h7.764v1.609h-5.929v1.641h5.017v1.608h-5.017v1.608h6.169v1.664Zm3.22-2.918v2.918h-1.881v-8.13h7.536v1.688H22.12v1.825h5.496v1.699H22.12Zm11.527-3.58v6.498h-1.961v-6.499h-2.92v-1.63h7.936v1.63h-3.055Z"/><path stroke="#000" stroke-linecap="round" stroke-width="1.331" d="M3.496 13.818h5.657M6.49 10.657h2.662M1 17.145h7.986"/></svg>
<YOUR SVG CODE>
</br
```

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

What's the expected date of this change to deploy on Shopify?

2023-06-14 14:29 UTC, Jacquesattaque requested changes
Why are you making changes to the workspace XML file as part of this PR? Should just be the YML file and your SVG.

2024-02-07 13:03 UTC, hellicarusprime commented
@jasonatyoco Your SVG doesn't follow the [contributing guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#guidelines-for-new-icons).

2024-10-03 17:15 UTC, dannye0231 commented
Hi @jasonatyoco, are you still planning to submit this icon using the changes mentioned by our team?

2025-01-10 19:53 UTC, closed without merging

2025-01-10 19:53 UTC, dannye0231 commented
Closed due to lack of response.  Please open a new PR if this change is still needed