Tilopay: Updates cuotas displaying icon
activemerchant/payment_icons pull request #911
Opened 2023-08-24 05:09 UTC by amurillotilopay

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [ ] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [ ] All icons have a corresponding entry in `db/payment_icons.yml`
- [ ] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [ ] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [ ] I am confident that all icons are clear and easy to read/understand
- [ ] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [ ] I have attached a screenshot comparison with the example icon provided in guidelines
- [ ] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon
![image](https://github.com/activemerchant/payment_icons/assets/98909129/0a8c63d3-e573-4454-a09f-b0e05dcfeb42)

#### Tips how to create a screenshot
We have found free online SVG editor https://www.freecodeformat.com/svg-editor.php very useful to create one. Here is a sample code for you to verify that you icon appears properly along side the placeholder.

```

<style> body { background: black; } </style>

<svg viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg" role="img" width="38" height="24" aria-labelledby="pi-visa"><title id="pi-visa">Visa</title><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path d="M28.3 10.1H28c-.4 1-.7 1.5-1 3h1.9c-.3-1.5-.3-2.2-.6-3zm2.9 5.9h-1.7c-.1 0-.1 0-.2-.1l-.2-.9-.1-.2h-2.4c-.1 0-.2 0-.2.2l-.3.9c0 .1-.1.1-.1.1h-2.1l.2-.5L27 8.7c0-.5.3-.7.8-.7h1.5c.1 0 .2 0 .2.2l1.4 6.5c.1.4.2.7.2 1.1.1.1.1.1.1.2zm-13.4-.3l.4-1.8c.1 0 .2.1.2.1.7.3 1.4.5 2.1.4.2 0 .5-.1.7-.2.5-.2.5-.7.1-1.1-.2-.2-.5-.3-.8-.5-.4-.2-.8-.4-1.1-.7-1.2-1-.8-2.4-.1-3.1.6-.4.9-.8 1.7-.8 1.2 0 2.5 0 3.1.2h.1c-.1.6-.2 1.1-.4 1.7-.5-.2-1-.4-1.5-.4-.3 0-.6 0-.9.1-.2 0-.3.1-.4.2-.2.2-.2.5 0 .7l.5.4c.4.2.8.4 1.1.6.5.3 1 .8 1.1 1.4.2.9-.1 1.7-.9 2.3-.5.4-.7.6-1.4.6-1.4 0-2.5.1-3.4-.2-.1.2-.1.2-.2.1zm-3.5.3c.1-.7.1-.7.2-1 .5-2.2 1-4.5 1.4-6.7.1-.2.1-.3.3-.3H18c-.2 1.2-.4 2.1-.7 3.2-.3 1.5-.6 3-1 4.5 0 .2-.1.2-.3.2M5 8.2c0-.1.2-.2.3-.2h3.4c.5 0 .9.3 1 .8l.9 4.4c0 .1 0 .1.1.2 0-.1.1-.1.1-.1l2.1-5.1c-.1-.1 0-.2.1-.2h2.1c0 .1 0 .1-.1.2l-3.1 7.3c-.1.2-.1.3-.2.4-.1.1-.3 0-.5 0H9.7c-.1 0-.2 0-.2-.2L7.9 9.5c-.2-.2-.5-.5-.9-.6-.6-.3-1.7-.5-1.9-.5L5 8.2z" fill="#142688"/></svg>

<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 38 24" width="38" height="24" aria-labelledby="pi-cuotas"><title id="pi-cuotas">Cuotas</title><path fill="#000" opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z"/><path fill="#fff" d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32"/><path opacity=".07" d="M35 0H3C1.3 0 0 1.3 0 3v18c0 1.7 1.4 3 3 3h32c1.7 0 3-1.3 3-3V3c0-1.7-1.4-3-3-3z" fill="#000"/><path d="M35 1c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H3c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2h32z" fill="#fff"/><path d="M22.162 7.33h1.87v1.129h.258c.243 0 .486-.004.725.003.03 0 .088.038.088.061.004.395.004.794.004 1.201h-1.068c-.004.053-.004.091-.004.13v2.139c0 .391.194.585.585.573.133-.003.266-.038.403-.057.053-.007.08-.034.08-.095 0-.9.524-1.352 1.231-1.577.46-.148.931-.197 1.41-.205.254-.004.513 0 .764 0 .11-.418-.076-.866-.4-.961a.956.956 0 00-.687.038c-.171.08-.205.14-.373.566h-1.744c.023-.144.038-.285.072-.422a1.777 1.777 0 011.114-1.277 3.805 3.805 0 012.702-.06c.706.243 1.086.771 1.17 1.508.015.13.023.262.023.395v3.492h-1.809v-.592c-.023.007-.034.007-.042.011-.285.395-.68.608-1.151.68-.452.073-.9.046-1.334-.125-.456-.182-.768-.505-.893-.992a.32.32 0 00-.038-.083v1.071c-.353.103-.703.175-1.06.156a3.514 3.514 0 01-.749-.099c-.63-.17-.984-.608-1.098-1.242a3.05 3.05 0 01-.046-.559c-.003-.638 0-1.277-.003-1.919 0-.16-.008-.323-.012-.483-.16-.003-.319-.011-.479-.015h-.16V8.451h.65V7.33zm5.996 4.347c-.068 0-.14-.004-.209 0-.243.012-.49.015-.722.122-.205.099-.304.277-.285.524.015.213.144.384.365.426.16.03.327.038.49.023.407-.046.688-.323.726-.692.011-.106 0-.213.004-.32.003-.06-.023-.083-.084-.083h-.285zM9.732 9.2c-.038.003-.08.003-.118.003-.65 0-1.3 0-1.95.004-.094 0-.125-.026-.144-.125a1.96 1.96 0 00-.144-.46c-.194-.395-.54-.57-.962-.593-.737-.038-1.273.297-1.512.996-.281.817-.281 1.649.057 2.455.24.57.703.843 1.322.855.38.007.73-.073 1.019-.339.254-.231.36-.535.414-.874H9.85c-.03.179-.046.358-.088.529-.262 1.159-.98 1.9-2.116 2.219a4.86 4.86 0 01-3.021-.11c-.98-.354-1.63-1.042-1.942-2.033-.308-.985-.338-1.988.004-2.968.463-1.33 1.432-2.098 2.804-2.356a4.522 4.522 0 012.261.144c1.08.354 1.706 1.11 1.927 2.212.026.129.038.262.057.391.003.02 0 .03-.004.05z" fill="#E4002B"/><path d="M21.755 11.176c0 .733-.198 1.394-.695 1.945-.441.487-1 .76-1.642.87-.733.126-1.452.073-2.132-.25-.912-.43-1.398-1.163-1.5-2.159-.058-.547-.005-1.079.212-1.588.3-.707.82-1.197 1.539-1.46.973-.353 1.938-.319 2.854.175.775.418 1.204 1.095 1.326 1.965.023.171.027.334.038.502zm-1.908.015c.008 0 .02-.004.027-.004-.038-.243-.057-.49-.122-.722-.129-.486-.478-.745-.972-.752-.49-.008-.852.243-1 .722a2.513 2.513 0 00.015 1.55c.152.464.494.688.988.684.456 0 .795-.247.95-.695.095-.255.122-.517.114-.783zM15.512 13.92h-1.859v-.791c-.007-.004-.015-.004-.019-.008-.015.027-.034.05-.049.076-.296.49-.741.753-1.3.829a2.281 2.281 0 01-.961-.054c-.695-.201-1.064-.695-1.197-1.383a3.05 3.05 0 01-.046-.558c-.003-1.144-.003-2.284-.003-3.428v-.137c.045-.004.08-.007.117-.007.54 0 1.08.003 1.62-.004.098 0 .128.026.128.129-.003 1.03-.003 2.056 0 3.086 0 .148.012.3.05.444.08.338.311.513.657.525.616.019.988-.327.996-.947.011-.991.004-1.983.004-2.975v-.25h1.858c.004 1.816.004 3.628.004 5.452zM35.397 10.077h-1.676c-.007-.015-.011-.03-.019-.045-.102-.346-.289-.494-.65-.49-.144 0-.292.03-.429.08-.16.056-.236.193-.232.364.004.164.118.259.255.293.277.068.558.106.84.167.36.08.73.14 1.079.258.585.194.93.608.984 1.24.042.493-.027.96-.346 1.363a1.622 1.622 0 01-.779.54c-.9.296-1.805.308-2.698-.011-.669-.24-1.052-.734-1.14-1.448-.007-.053 0-.11 0-.175.034-.004.069-.008.107-.008.497 0 .999 0 1.497-.003.08 0 .114.026.129.106.072.315.258.479.585.498.156.007.316-.008.468-.023.064-.008.129-.046.19-.08.197-.114.288-.494-.027-.623-.209-.084-.433-.13-.654-.179-.387-.087-.782-.155-1.17-.247a1.542 1.542 0 01-.372-.163c-.4-.217-.608-.562-.67-1.003a2.06 2.06 0 01.031-.821c.156-.578.555-.927 1.09-1.136.533-.21 1.088-.243 1.646-.183.285.03.574.092.844.187.65.231.992.722 1.098 1.394.008.046.011.095.015.14.008-.007.008-.003.004.008z" fill="#E4002B"/><path d="M5.556 14.903c.235 0 .364.114.402.354l.004.019h.228v-.023c-.023-.338-.262-.551-.623-.551-.502 0-.882.422-.882.977 0 .444.293.73.741.73a.72.72 0 00.719-.575l.007-.03h-.235l-.004.015c-.076.247-.251.384-.483.384-.323 0-.494-.182-.494-.528-.004-.46.247-.772.62-.772zM6.958 15.143c-.373 0-.65.308-.65.718 0 .327.22.547.551.547.38 0 .654-.304.654-.722-.004-.327-.225-.543-.555-.543zm-.095 1.064c-.205 0-.32-.126-.32-.35 0-.304.164-.517.4-.517.205 0 .319.126.319.35.004.308-.156.517-.4.517zM9.105 15.139a.48.48 0 00-.4.22c-.045-.144-.159-.22-.33-.22a.441.441 0 00-.346.179c.004-.042.004-.088.004-.137v-.023h-.22v.023a3.09 3.09 0 01-.03.35l-.137.854h.235l.114-.722c.034-.22.194-.323.338-.323.065 0 .11.02.141.054.038.045.05.117.034.216l-.121.772h.235l.114-.722c.038-.22.194-.323.338-.323.069 0 .114.015.141.049.038.046.05.122.03.232l-.117.76h.235l.114-.722c.03-.183.004-.323-.072-.414a.448 [...]

2023-08-24 05:12 UTC, amurillotilopay commented
@hnannetilo @adeniyiao .

Hi.

Here is the new PR updating the cuotas icon.

2023-08-24 15:56 UTC, Jacquesattaque requested changes
Icon has two 7% black borders on top of one another, resulting in a 14% black border. Please remove the duplicate layers from the SVG and resubmit.

2023-08-25 00:44 UTC, amurillotilopay commented
> Icon has two 7% black borders on top of one another, resulting in a 14% black border. Please remove the duplicate layers from the SVG and resubmit.

@Jacquesattaque Change applied.

2023-08-25 18:21 UTC, Jacquesattaque approved these changes

2023-09-06 11:42 UTC, merged