Added Pay by Bank logo
activemerchant/payment_icons pull request #943
Opened 2023-10-13 21:08 UTC by burgaard

## Why are you adding this icons?
I'm adding/updating this icon(s) because ..

#### Help us identify yourself
- [ ] I'm working/collaborating with the brand directly and they have provided the icons.
- [x] I'm associated with the brand and I've read all the brand icon’s guidelines.
- [ ] I'm an individual and I've read all the brand icon’s guidelines.

Link to the brand guidelines: <Link>

## Checklist to add new icons
- [x] All icons have a corresponding entry in `db/payment_icons.yml`
- [x] I have followed the icon guidelines detailed in the [CONTRIBUTING.md](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) file
- [x] I have optimized the icon with [SVGO](https://jakearchibald.github.io/svgomg/)
- [x] I am confident that all icons are clear and easy to read/understand
- [x] I have provided a link to the brand icon’s brand guidelines whenever possible.
- [x] I have attached a screenshot comparison with the example icon provided in guidelines
- [x] I recognize that if my icon is not approved by the Shopify Partners team it may not receive review nor merger.

If this pull request is not adding new icons, you can remove this checklist.

## Attach a screenshot of the icon along side the example Visa icon

<img width="90" alt="Screenshot 2023-10-13 at 2 06 16 PM" src="https://github.com/activemerchant/payment_icons/assets/1544532/705b3bca-3f19-4186-b7c8-247d67e3d58e">
<img width="425" alt="Screenshot 2023-10-13 at 2 06 24 PM" src="https://github.com/activemerchant/payment_icons/assets/1544532/47e55f84-0524-43be-8d1e-367069924e6e">

#### If the icons are intended for use by Shopify, please provide the following info:
Who are you working with at Shopify? (avoid adding personal details, provide github handle(preferred) or first name and last name)

@Jacquesattaque 

Marlena Spidalieri

What's the expected date of this change to deploy on Shopify?

As soon as possible.

2023-10-16 19:30 UTC, Jacquesattaque commented
@burgaard If the intention of this icon is to highlight a generic payment method, I'd recommend using our generic [online banking icon](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/onlinebanking.svg). We're working on integrating this with merchant branding in checkout as well so it will seamlessly adapt to any merchant checkout customizations.

2023-10-17 21:38 UTC, burgaard commented
@Jacquesattaque this is not generic -- it's our Pay by Bank logo, font and color style consistent with the rest of our branding

2023-10-17 21:46 UTC, Jacquesattaque commented
@burgaard In that case there is already a Pay By Bank payment method and icon. Are you trying to replace that one, or is this new? If it's new, you'll need to choose a new name for this payment method. Underscores are not permitted in the name.

2023-10-18 17:50 UTC, burgaard commented
@Jacquesattaque it's our unique logo -- we are not trying to replace any of the existing logos. I'm confused about the underscore requirement -- there are lots of other entries with underscores in the name field?

2023-10-18 20:54 UTC, burgaard commented
OK, I've updated the name @Jacquesattaque

2023-10-19 15:38 UTC, Jacquesattaque requested changes
Two changes to the icon:

- Looks like you have the border and background layers duplicated here. Remove one set.
- There are quite a few unnecessary points in drawing the letters, which is increasing file size. Try to simplify this to reduce file size.

![Screenshot 2023-10-19 at 9 37 02 AM](https://github.com/activemerchant/payment_icons/assets/3044568/60d4bce2-5085-4461-9c1f-02d0d0847860)

2023-10-20 19:05 UTC, burgaard commented
@Jacquesattaque I've fixed the duplicated borders. The vector points for the letters are simply just how the font is rendered in the SVG export.

2023-10-21 15:12 UTC, Jacquesattaque approved these changes

2023-10-25 18:25 UTC, burgaard commented
@Jacquesattaque do you have an estimate when this might be available on Shopify?

2023-10-25 19:20 UTC, Jacquesattaque commented
@burgaard We do a monthly release, typically on the first Wednesday of the month. The next release is tentatively scheduled for next Wednesday, November 1.

2023-11-01 15:13 UTC, adeniyiao commented
Hi @burgaard 

Could you please rebase this branch with activemerchant/master to resolve the conflicts.

Thanks

2023-11-01 15:24 UTC, burgaard commented
Done @adeniyiao!

2023-11-01 15:41 UTC, adeniyiao commented
Thanks for quick response @burgaard , kindly fix the test failure below. 

<img width="670" alt="image" src="https://github.com/activemerchant/payment_icons/assets/97685764/96f8425b-fd3b-4bbb-8e4b-73a2e83d9836">

2023-11-01 15:48 UTC, adeniyiao commented on db/payment_icons.yml
> +  name: mpesa
Unexpected change here as well

2023-11-01 16:16 UTC, burgaard commented
@adeniyiao should be fixed now!

2023-11-01 16:16 UTC, burgaard commented on db/payment_icons.yml
> +  name: mpesa
Not sure where that came from. Fixed!

2023-11-01 16:21 UTC, merged